import { ThresholdDefinition } from '../../types/knowledge';

/**
 * Salud Canonical Threshold Registry (vNext.8.1 P2)
 * Centralized registry for all clinical diagnostic cutoffs, policy thresholds, and laboratory targets.
 */
export const CANONICAL_THRESHOLDS: ThresholdDefinition[] = [
  // --- Blood Pressure (AHA/ACC 2025) ---
  {
    id: 'TH-BP-NORMAL',
    topic: 'blood_pressure',
    metric_name: 'Blood Pressure',
    metric_name_zh: '正常血壓',
    unit: 'mmHg',
    operator: '<',
    value: 120,
    value_upper: 80,
    clinical_category_zh: '正常血壓 (Normal)',
    clinical_category_en: 'Normal Blood Pressure',
    guideline_authority: 'AHA/ACC 2025',
    guideline_year: 2025,
    target_population_zh: '一般成人 (>=18歲)',
    measurement_context_zh: '依標準量測規範，靜坐5分鐘後多次診間量測之平均值',
    actionable_implication_zh: '維持健康生活型態，每年至少定期測量一次。',
    canonical_atom_id: 'KA-BP-001',
    canonical_claim_id: 'CLAIM-BP-AHA-2025',
  },
  {
    id: 'TH-BP-STAGE1',
    topic: 'blood_pressure',
    metric_name: 'Blood Pressure Stage 1',
    metric_name_zh: '第 1 期高血壓',
    unit: 'mmHg',
    operator: 'range',
    value: 130,
    value_upper: 139,
    clinical_category_zh: '第 1 期高血壓 (Stage 1 Hypertension)',
    clinical_category_en: 'Stage 1 Hypertension',
    guideline_authority: 'AHA/ACC 2025',
    guideline_year: 2025,
    target_population_zh: '一般成人 (>=18歲)',
    measurement_context_zh: '收縮壓 130–139 或 舒張壓 80–89 mmHg（多次平均）',
    actionable_implication_zh: '若 PREVENT 10年心血管風險 <7.5%，可先進行 3–6 個月生活型態介入；若 >=7.5% 則應即時評估藥物治療。',
    contraindications_or_exclusions_zh: '已確立心血管疾病、糖尿病或 CKD 患者不適用觀察期，應直接就醫。',
    canonical_atom_id: 'KA-BP-001',
    canonical_claim_id: 'CLAIM-BP-AHA-2025',
  },
  {
    id: 'TH-BP-TARGET',
    topic: 'blood_pressure',
    metric_name: 'Blood Pressure Treatment Target',
    metric_name_zh: '成人常規血壓治療目標',
    unit: 'mmHg',
    operator: '<',
    value: 130,
    value_upper: 80,
    clinical_category_zh: '治療目標 (Treatment Target)',
    clinical_category_en: 'Treatment Target',
    guideline_authority: 'AHA/ACC 2025',
    guideline_year: 2025,
    target_population_zh: '接受高血壓治療之成人',
    measurement_context_zh: '標準化血壓量測平均值',
    actionable_implication_zh: '目標將血壓穩定控制於 <130/80 mmHg，以降低心肌梗塞、中風與心衰竭事件。',
    contraindications_or_exclusions_zh: '懷孕、長照衰弱長者、重大共病或預期餘命有限者須由臨床醫師個別訂定較寬鬆目標。',
    canonical_atom_id: 'KA-BP-002',
    canonical_claim_id: 'CLAIM-BP-AHA-2025',
  },
  {
    id: 'TH-BP-PREVENT-HIGH',
    topic: 'blood_pressure',
    metric_name: 'PREVENT 10-Year CVD Risk High Threshold',
    metric_name_zh: 'PREVENT 10 年高心血管風險切點',
    unit: '%',
    operator: '>=',
    value: 7.5,
    clinical_category_zh: '高心血管風險 (High 10-Year ASCVD Risk)',
    clinical_category_en: 'High CVD Risk',
    guideline_authority: 'AHA/ACC 2025',
    guideline_year: 2025,
    target_population_zh: '30–79 歲無既往臨床心血管疾病成人',
    measurement_context_zh: '依 AHA PREVENT 方程計算（整合年齡、血壓、血脂、eGFR、尿白蛋白、糖尿病狀態）',
    actionable_implication_zh: '第 1 期高血壓合併 PREVENT >=7.5% 者應即刻評估起始藥物治療，不可僅依賴生活型態觀察期。',
    canonical_atom_id: 'KA-BP-003',
  },

  // --- Glycemic Control (ADA 2026 Living Guideline) ---
  {
    id: 'TH-GL-A1C-DIABETES',
    topic: 'glucose',
    metric_name: 'Hemoglobin A1C Diabetes Cutoff',
    metric_name_zh: '糖化血色素糖尿病診斷切點',
    unit: '%',
    operator: '>=',
    value: 6.5,
    clinical_category_zh: '糖尿病診斷 (Diabetes Mellitus)',
    clinical_category_en: 'Diabetes Mellitus',
    guideline_authority: 'ADA Standards of Care 2026 §2',
    guideline_year: 2026,
    target_population_zh: '成人',
    measurement_context_zh: '採用 NGSP 認證且標準化至 DCCT 分析之檢驗方法',
    actionable_implication_zh: '無典型高血糖急性症狀者，需於同日不同檢驗或兩次不同採樣確認。',
    contraindications_or_exclusions_zh: '溶血性貧血、血紅素變異體、近期輸血、懷孕、終末期腎病者 A1C 易失真，需改用血糖檢驗。',
    canonical_atom_id: 'KA-GL-001',
    canonical_claim_id: 'CLAIM-GL-A1C-DIAB',
  },
  {
    id: 'TH-GL-FPG-DIABETES',
    topic: 'glucose',
    metric_name: 'Fasting Plasma Glucose Diabetes Cutoff',
    metric_name_zh: '空腹血糖糖尿病診斷切點',
    unit: 'mg/dL',
    operator: '>=',
    value: 126,
    clinical_category_zh: '糖尿病診斷 (Diabetes Mellitus)',
    clinical_category_en: 'Diabetes Mellitus',
    guideline_authority: 'ADA Standards of Care 2026 §2',
    guideline_year: 2026,
    target_population_zh: '成人',
    measurement_context_zh: '禁食至少 8 小時之靜脈血漿血糖',
    actionable_implication_zh: '需重複檢驗確認或搭配 A1C / OGTT。',
    canonical_atom_id: 'KA-GL-001',
    canonical_claim_id: 'CLAIM-GL-FPG-DIAB',
  },
  {
    id: 'TH-GL-A1C-PREDIABETES',
    topic: 'glucose',
    metric_name: 'A1C Prediabetes Range',
    metric_name_zh: '糖尿病前期 A1C 區間',
    unit: '%',
    operator: 'range',
    value: 5.7,
    value_upper: 6.4,
    clinical_category_zh: '糖尿病前期 (Prediabetes)',
    clinical_category_en: 'Prediabetes',
    guideline_authority: 'ADA Standards of Care 2026 §2',
    guideline_year: 2026,
    target_population_zh: '成人',
    measurement_context_zh: 'NGSP 認證檢驗法',
    actionable_implication_zh: '代謝風險警告狀態；建議生活型態介入（減重 7%、每週 >=150 分鐘運動）可顯著降低轉變為第2型糖尿病機率。',
    canonical_atom_id: 'KA-GL-002',
    canonical_claim_id: 'CLAIM-GL-A1C-PREDIAB',
  },

  // --- Lipids (2026 ACC/AHA Multisociety) ---
  {
    id: 'TH-LP-LDL-GENERAL',
    topic: 'lipids',
    metric_name: 'LDL-C General Primary Target',
    metric_name_zh: '一般成人 LDL-C 治療目標',
    unit: 'mg/dL',
    operator: '<',
    value: 100,
    clinical_category_zh: '一般風險目標 (General Risk Target)',
    clinical_category_en: 'General Target',
    guideline_authority: '2026 ACC/AHA Multisociety Lipid Guideline',
    guideline_year: 2026,
    target_population_zh: '低至中度風險之一般成人',
    measurement_context_zh: '空腹或非空腹常規血脂分析',
    actionable_implication_zh: '基礎血脂健康標竿；若合併高風險因子應追求更嚴格階梯階層。',
    canonical_atom_id: 'KA-LP-001',
    canonical_claim_id: 'CLAIM-LP-LDL-TARGET',
  },
  {
    id: 'TH-LP-LDL-HIGH',
    topic: 'lipids',
    metric_name: 'LDL-C High Risk Target',
    metric_name_zh: '高風險成人 LDL-C 階梯目標',
    unit: 'mg/dL',
    operator: '<',
    value: 70,
    clinical_category_zh: '高心血管風險目標 (High Risk Target)',
    clinical_category_en: 'High Risk Target',
    guideline_authority: '2026 ACC/AHA Multisociety Lipid Guideline',
    guideline_year: 2026,
    target_population_zh: '確立心血管疾病、糖尿病合併多重心血管風險因子者',
    measurement_context_zh: '血脂常規檢查',
    actionable_implication_zh: '高強度生活型態搭配他汀類/非他汀降脂藥物組合。',
    canonical_atom_id: 'KA-LP-001',
    canonical_claim_id: 'CLAIM-LP-LDL-HIGH-RISK',
  },
  {
    id: 'TH-LP-LPA-RISK',
    topic: 'lipids',
    metric_name: 'Lipoprotein(a) Elevated ASCVD Risk',
    metric_name_zh: 'Lp(a) 升高 ASCVD 風險切點',
    unit: 'nmol/L',
    operator: '>',
    value: 125,
    clinical_category_zh: 'Lp(a) 升高風險區間 (Elevated Lp(a))',
    clinical_category_en: 'Elevated Lp(a)',
    guideline_authority: '2026 ACC/AHA Multisociety Lipid Guideline',
    guideline_year: 2026,
    target_population_zh: '成人一生建議至少檢驗一次',
    measurement_context_zh: '以 nmol/L 報告之同工型不敏感方法（Isoform-insensitive assays）',
    actionable_implication_zh: '>125 nmol/L 對應約 1.4 倍 ASCVD 風險；>250 nmol/L 對應 >=2.0 倍。作為終生獨立風險再分層依據。',
    contraindications_or_exclusions_zh: 'nmol/L 與 mg/dL 因 Apolipoprotein(a) 分子異質性，絕不可用固定常數換算！',
    canonical_atom_id: 'KA-LP-002',
    canonical_claim_id: 'CLAIM-LP-LPA-RISK-125',
  },

  // --- Taiwan Statutory Body Composition (HPA) ---
  {
    id: 'TH-TW-BMI-NORMAL',
    topic: 'body_composition',
    metric_name: 'Taiwan Adult Healthy BMI Range',
    metric_name_zh: '台灣成人健康體位標準 BMI 區間',
    unit: 'kg/m²',
    operator: 'range',
    value: 18.5,
    value_upper: 23.9,
    clinical_category_zh: '正常體位 (Normal BMI)',
    clinical_category_en: 'Normal BMI (Taiwan)',
    guideline_authority: '台灣衛生福利部國民健康署 (HPA)',
    guideline_year: 2024,
    target_population_zh: '台灣滿 18 歲以上成人',
    measurement_context_zh: '標準身高體重計脫鞋脫重外套量測',
    actionable_implication_zh: '東亞族群內臟脂肪累積敏感度高，故台灣過重切點為 24、肥胖切點為 27，低於西方 WHO 25/30 切點。',
    canonical_atom_id: 'KA-TW-001',
    canonical_claim_id: 'CLAIM-TW-BMI-NORMAL-MIN',
  },
  {
    id: 'TH-TW-WC-CENTRAL-OBESITY-M',
    topic: 'body_composition',
    metric_name: 'Taiwan Waist Circumference Male Cutoff',
    metric_name_zh: '台灣男性腰圍腹部肥胖切點',
    unit: 'cm',
    operator: '>=',
    value: 90,
    clinical_category_zh: '男性腹部肥胖 (Central Obesity, Male)',
    clinical_category_en: 'Central Obesity (Male)',
    guideline_authority: '台灣衛生福利部國民健康署 (HPA)',
    guideline_year: 2024,
    target_population_zh: '台灣成年男性',
    measurement_context_zh: '呼氣末期量測肋骨下緣與髂骨上緣中線之水平腰圍',
    actionable_implication_zh: '即使 BMI 正常，若腰圍 >=90 cm 仍屬代謝症候群與心血管高風險族群。',
    canonical_atom_id: 'KA-TW-002',
    canonical_claim_id: 'CLAIM-TW-WC-MALE',
  },
  {
    id: 'TH-TW-WC-CENTRAL-OBESITY-F',
    topic: 'body_composition',
    metric_name: 'Taiwan Waist Circumference Female Cutoff',
    metric_name_zh: '台灣女性腰圍腹部肥胖切點',
    unit: 'cm',
    operator: '>=',
    value: 80,
    clinical_category_zh: '女性腹部肥胖 (Central Obesity, Female)',
    clinical_category_en: 'Central Obesity (Female)',
    guideline_authority: '台灣衛生福利部國民健康署 (HPA)',
    guideline_year: 2024,
    target_population_zh: '台灣成年女性',
    measurement_context_zh: '呼氣末期量測肋骨下緣與髂骨上緣中線之水平腰圍',
    actionable_implication_zh: '女性腰圍 >=80 cm 具獨立胰島素阻抗與內臟脂肪風險。',
    canonical_atom_id: 'KA-TW-002',
    canonical_claim_id: 'CLAIM-TW-WC-FEMALE',
  },

  // --- KDIGO 2024 Renal CGA Staging ---
  {
    id: 'TH-KD-CKD-G4-SEVERE',
    topic: 'kidney',
    metric_name: 'KDIGO eGFR Stage G4 Severe Impairment',
    metric_name_zh: '慢性腎臟病 G4 期重度腎功能衰竭',
    unit: 'mL/min/1.73m²',
    operator: 'range',
    value: 15,
    value_upper: 29,
    clinical_category_zh: 'CKD G4 期 (Severe eGFR Reduction)',
    clinical_category_en: 'CKD Stage G4',
    guideline_authority: 'KDIGO 2024 CKD Clinical Practice Guideline',
    guideline_year: 2024,
    target_population_zh: '腎功能損害持續 >= 3 個月之成人',
    measurement_context_zh: 'CKD-EPI 2021 肌酸酐推算之 eGFR',
    actionable_implication_zh: '絕對禁用常規多喝水與高鉀飲食建議！強烈需要腎臟科專業個人化液體與電解質限制。',
    contraindications_or_exclusions_zh: '啟動 PRED-CKD-G4-G5 安全攔阻謂詞。',
    canonical_atom_id: 'KA-KD-002',
    canonical_claim_id: 'CLAIM-KD-CKD-G4-MIN',
  },

  // --- Sodium & Potassium (WHO 2013) ---
  {
    id: 'TH-NA-DAILY-MAX',
    topic: 'sodium_potassium',
    metric_name: 'WHO Daily Sodium Ceiling',
    metric_name_zh: 'WHO 成人每日鈉攝取上限',
    unit: 'mg/day',
    operator: '<',
    value: 2000,
    clinical_category_zh: '鈉攝取上限目標 (Sodium Ceiling)',
    clinical_category_en: 'Sodium Ceiling',
    guideline_authority: 'WHO 2013 Sodium Intake for Adults and Children',
    guideline_year: 2013,
    target_population_zh: '一般健康成人',
    measurement_context_zh: '每日飲食總鈉（含調味料與加工食品），相當於食鹽 <5 公克',
    actionable_implication_zh: '控制每日鈉攝取低於 2000 mg，以維持健康血壓並預防心血管疾病。',
    canonical_atom_id: 'KA-NA-001',
    canonical_claim_id: 'CLAIM-NA-WHO-LIMIT',
  },
  {
    id: 'TH-K-DAILY-ADEQUATE',
    topic: 'sodium_potassium',
    metric_name: 'WHO Daily Potassium Adequate Target',
    metric_name_zh: 'WHO 成人每日鉀建議攝取量',
    unit: 'mg/day',
    operator: '>=',
    value: 3510,
    clinical_category_zh: '充足鉀攝取目標 (Adequate Potassium)',
    clinical_category_en: 'Adequate Potassium',
    guideline_authority: 'WHO 2013 Potassium Intake for Adults and Children',
    guideline_year: 2013,
    target_population_zh: '腎功能正常之健康成人',
    measurement_context_zh: '來自新鮮蔬果與全穀類之天然膳食鉀',
    actionable_implication_zh: '高鉀有助於促進尿鈉排泄並拮抗交感神經張力。',
    contraindications_or_exclusions_zh: '中晚期腎病（CKD G4–G5）、使用保鉀利尿劑或 RAAS 抑制劑者禁用此建議（有致命性高血鉀風險）。',
    canonical_atom_id: 'KA-NA-001',
    canonical_claim_id: 'CLAIM-K-WHO-TARGET',
  },

  // --- Fats (WHO 2023) ---
  {
    id: 'TH-FAT-SFA-RATIO',
    topic: 'fats',
    metric_name: 'WHO Saturated Fatty Acid Energy Ratio',
    metric_name_zh: 'WHO 飽和脂肪酸能量比例上限',
    unit: '%E',
    operator: '<',
    value: 10,
    clinical_category_zh: '飽和脂肪上限比例 (SFA Ratio Ceiling)',
    clinical_category_en: 'SFA Limit %E',
    guideline_authority: 'WHO 2023 Saturated and Trans-fatty Acid Intake',
    guideline_year: 2023,
    target_population_zh: '成人與兒童 (>=2歲)',
    measurement_context_zh: '相對總熱量百分比（以 2000 kcal 換算約 22 克/日）',
    actionable_implication_zh: '必須同時顯示比例與依個人攝取熱量動態換算之克數。',
    canonical_atom_id: 'KA-O-001',
    canonical_claim_id: 'CLAIM-O-WHO-SFA-PCT',
  },

  // --- Commercial Frying Oil (TFDA) ---
  {
    id: 'TH-OIL-TPC-VIOLATION',
    topic: 'fats',
    metric_name: 'Taiwan Commercial Frying Oil TPC Violation Cutoff',
    metric_name_zh: '台灣餐飲業油炸油總極性化合物違規切點',
    unit: '%',
    operator: '>',
    value: 25,
    clinical_category_zh: '油品劣變違規 (Commercial Oil Deterioration)',
    clinical_category_en: 'TPC Violation Standard',
    guideline_authority: '台灣衛生福利部食品藥物管理署 (TFDA)',
    guideline_year: 2011,
    target_population_zh: '台灣餐飲營業場所',
    measurement_context_zh: '酸價 >2.0 時以標準層析法加驗之總極性化合物比例',
    actionable_implication_zh: 'TPC >25% 即屬劣變油品，依法令不得繼續供作食品煎炸使用。',
    contraindications_or_exclusions_zh: '此為官方稽查標準，家庭廚房應以顏色、黏稠度、起泡程度為實用汰換依據。',
    canonical_atom_id: 'KA-O-004',
    canonical_claim_id: 'CLAIM-O-TFDA-TPC',
  },

  // --- ALDH2 rs671 Residual Activity Ranges ---
  {
    id: 'TH-ALDH2-HETERO-RANGE',
    topic: 'alcohol_aldh2',
    metric_name: 'ALDH2 Heterozygous *1/*2 Residual Activity',
    metric_name_zh: 'ALDH2 *1/*2 雜合突變殘餘酵素活性區間',
    unit: '%',
    operator: 'range',
    value: 10,
    value_upper: 38,
    clinical_category_zh: '顯著活性下降 (Substantially Reduced ALDH2 Activity)',
    clinical_category_en: 'Reduced Activity Range',
    guideline_authority: 'Frontiers in Pharmacology 2026 & Pharmacogenetics Studies',
    guideline_year: 2026,
    target_population_zh: '東亞族群 rs671 *1/*2 帶因者（台灣約 45–47%）',
    measurement_context_zh: '依不同組織樣本與活體外分析方法，報告為約 10% 至 17–38% 之範圍',
    actionable_implication_zh: '方法學依賴區間，不可宣稱為固定點值。即使少量飲酒亦導致全身乙醛急性蓄積。',
    canonical_atom_id: 'KA-A-002',
    canonical_claim_id: 'CLAIM-A-ALDH2-HETERO-MIN',
  },
  {
    id: 'TH-ALDH2-HOMO-NEAR-ZERO',
    topic: 'alcohol_aldh2',
    metric_name: 'ALDH2 Homozygous *2/*2 Residual Activity',
    metric_name_zh: 'ALDH2 *2/*2 純合突變殘餘酵素活性',
    unit: '%',
    operator: '<=',
    value: 1,
    clinical_category_zh: '酵素活性喪失 (Near-Zero ALDH2 Activity)',
    clinical_category_en: 'Near Zero Activity',
    guideline_authority: 'Pharmacogenetics Literature & IARC Monograph',
    guideline_year: 2026,
    target_population_zh: '東亞族群 rs671 *2/*2 純合缺失者',
    measurement_context_zh: '線粒體 ALDH2 四聚體失去結合催化活性',
    actionable_implication_zh: '體內無法有效代謝乙醛，嚴禁任何飲酒，BAC 計算結果無法代表乙醛毒性安全！',
    contraindications_or_exclusions_zh: '觸發 PRED-ALDH2-DEFICIENT 強制警語與安全防護攔截。',
    canonical_atom_id: 'KA-A-002',
    canonical_claim_id: 'CLAIM-A-ALDH2-HOMO',
  },
];

export const CANONICAL_THRESHOLD_MAP: Record<string, ThresholdDefinition> = Object.fromEntries(
  CANONICAL_THRESHOLDS.map((t) => [t.id, t])
);
