/**
 * pack82.ts — Canonical Knowledge Pack vNext.8 (82 Core Knowledge Atoms)
 *
 * Seed collection of deterministic, provenance-backed, population-aware,
 * misuse-guarded medical knowledge atoms.
 */

import { KnowledgeAtom } from '../../types/knowledge';
import { CANONICAL_PAPER_REGISTRY } from '../sources/paperRegistry';
import { CANONICAL_CLINICAL_MASTERY_REGISTRY } from '../mastery/clinicalMasteryRegistry';

const RAW_CANONICAL_KNOWLEDGE_PACK_82: KnowledgeAtom[] = [
  // ==========================================
  // 8.A 血壓 (Tier 1 核心節點)
  // ==========================================
  {
    id: 'KA-BP-001',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R3',
    topic: 'blood_pressure',
    statement_zh:
      '成人血壓分級（2025 AHA/ACC）：正常 <120/<80；升高 120–129/<80；第 1 期高血壓 130–139 或 80–89；第 2 期高血壓 ≥140 或 ≥90 mmHg。',
    applies_to: { population: '一般成年人', region: '全球' },
    primary_source: 'SRC-AHA-ACC-2025-HTN',
    evidence_records: [
      {
        id: 'EV-BP-001',
        citation: '2025 AHA/ACC Hypertension Guideline',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-BP-NORMAL', 'TH-BP-STAGE1'],
    ontology: {
      mesh_id: 'D006973',
      mesh_term: 'Hypertension',
      icd11_code: 'BA00',
      snomed_ct: '38341003',
    },
    misuse_guard: '單次診間量測不足以分級；須符合標準量測程序（安靜坐姿 5 分鐘、排空膀胱）之多次平均。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-BP-002',
    assertion_kind: 'policy',
    risk_class: 'R3',
    topic: 'blood_pressure',
    statement_zh: '2025 指引維持一般成年人治療目標為收縮壓與舒張壓 <130/80 mmHg。',
    applies_to: { population: '成年高血壓患者', region: '全球' },
    primary_source: 'SRC-AHA-ACC-2025-HTN',
    evidence_records: [
      {
        id: 'EV-BP-002',
        citation: '2025 AHA/ACC Hypertension Guideline Table 8',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-BP-TARGET'],
    ontology: {
      mesh_id: 'D006973',
      mesh_term: 'Hypertension',
      icd11_code: 'BA00',
    },
    misuse_guard: '懷孕、長照機構長者、預期餘命有限或嚴重姿勢性低血壓者另有特殊目標，不可一律套用。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-BP-003',
    assertion_kind: 'quantitative',
    risk_class: 'R2',
    topic: 'blood_pressure',
    statement_zh:
      '2025 指引改用 PREVENT 心血管風險方程，高風險閾值由原 PCE 方程之 10 年 ≥10% 下調為 PREVENT 10 年 ≥7.5%。',
    applies_to: { population: '30–79 歲成年人', region: '全球' },
    primary_source: 'SRC-AHA-ACC-2025-HTN',
    evidence_records: [
      {
        id: 'EV-BP-003',
        citation: 'Circulation 2024; PREVENT Risk Equations Validation',
        design: 'cohort',
        sample_size: 6000000,
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    threshold_ids: ['TH-BP-PREVENT-HIGH'],
    misuse_guard: 'PREVENT 與 PCE 分數不可互換比較；計算門檻數值改變不等於個人心血管風險突然改變。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-BP-004',
    assertion_kind: 'procedural',
    risk_class: 'R2',
    topic: 'blood_pressure',
    statement_zh:
      '第 1 期高血壓且低心血管風險（PREVENT <7.5%）者，先行 3–6 個月積極生活型態調整；若平均血壓仍 ≥130/80 mmHg 再起始降壓藥物。',
    applies_to: { population: '低心血管風險第 1 期高血壓成人', region: '全球' },
    primary_source: 'SRC-AHA-ACC-2025-HTN',
    evidence_records: [
      {
        id: 'EV-BP-004',
        citation: '2025 AHA/ACC Hypertension Guideline Section 4.2',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '已有心血管疾病 (CVD)、糖尿病、慢性腎臟病 (CKD) 或 PREVENT ≥7.5% 者不適用此觀察期，應立即合併藥物。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-BP-005',
    assertion_kind: 'mechanism',
    risk_class: 'R1',
    topic: 'blood_pressure',
    statement_zh:
      '機制鏈：高鈉負荷 → 細胞外液量上升 → 心輸出量與血管阻力重設 → 壓力自然尿鈉排泄曲線右移 → 維持鈉平衡所需血壓升高。',
    applies_to: { population: '一般生理學', region: '全球' },
    primary_source: 'Guyton and Hall Textbook of Medical Physiology, 14th Ed.',
    evidence_records: [
      {
        id: 'EV-BP-005',
        citation: 'Guyton & Hall Physiology Ch. 19',
        design: 'mechanistic_in_vitro',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '鈉敏感性存在高度個體差異，不可推論「每個人減鈉都會降下同等毫米汞柱」。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // ==========================================
  // 8.B 血糖 (Tier 1 核心節點)
  // ==========================================
  {
    id: 'KA-GL-001',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R3',
    topic: 'glucose',
    statement_zh:
      '糖尿病診斷符合任一項：A1C ≥6.5%（≥48 mmol/mol）；空腹血漿葡萄糖 FPG ≥126 mg/dL（≥7.0 mmol/L）；75g OGTT 2 小時血糖 ≥200 mg/dL；或具典型高血糖症狀下隨機血糖 ≥200 mg/dL。',
    applies_to: { population: '成人', region: '全球' },
    primary_source: 'SRC-ADA-2026',
    evidence_records: [
      {
        id: 'EV-GL-001',
        citation: 'ADA Standards of Care 2026 Section 2',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-GL-A1C-DIABETES', 'TH-GL-FPG-DIABETES'],
    ontology: {
      mesh_id: 'D003920',
      mesh_term: 'Diabetes Mellitus',
      icd11_code: '5A11',
      snomed_ct: '73211009',
    },
    misuse_guard:
      '無明確高血糖危象之無症狀者，須於同一樣本採用兩種檢驗或兩次採樣異常確認；A1C 須使用 NGSP 認證方法。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-GL-002',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R3',
    topic: 'glucose',
    statement_zh:
      '糖尿病前期 (Prediabetes) 定義：A1C 5.7–6.4%；空腹血糖異常 (IFG) 為 FPG 100–125 mg/dL；耐糖不良 (IGT) 為 75g OGTT 2 小時 140–199 mg/dL。',
    applies_to: { population: '成人', region: '全球' },
    primary_source: 'SRC-ADA-2026',
    evidence_records: [
      {
        id: 'EV-GL-002',
        citation: 'ADA Standards of Care 2026 Section 2',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-GL-A1C-PREDIABETES'],
    ontology: {
      mesh_id: 'D011236',
      mesh_term: 'Prediabetic State',
      icd11_code: '5A40',
    },
    misuse_guard: '「糖尿病前期」代表代謝風險增高狀態，並非確定疾病診斷，亦不代表必然無可挽回進展為糖尿病。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-GL-003',
    assertion_kind: 'policy',
    risk_class: 'R2',
    topic: 'glucose',
    statement_zh: '指引建議所有無症狀成年人應自 35 歲起常態篩檢糖尿病前期與第 2 型糖尿病。',
    applies_to: { population: '成人 (美加指引基準)', region: '全球' },
    primary_source: 'SRC-ADA-2026',
    evidence_records: [
      {
        id: 'EV-GL-003',
        citation: 'ADA Standards of Care 2026 Screening',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '過重/肥胖且具危險因子者應提前；此為指引篩檢基準，台灣健保成人預防保健之公費年齡另計。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-GL-004',
    assertion_kind: 'context',
    risk_class: 'R2',
    topic: 'glucose',
    statement_zh: 'ADA 自 2026 年起全面轉為「活體指引（Living Guideline）」模式，全年線上即時滾動更新。',
    applies_to: { population: '醫療專業人員與衛教架構', region: '全球' },
    primary_source: 'SRC-ADA-2026',
    evidence_records: [
      {
        id: 'EV-GL-004',
        citation: 'Diabetes Care 2026 Living Guideline Announcement',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '架構規範：引用 ADA 血糖門檻必須帶版本號與檢索日期，年度快照式引用不再足夠。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-GL-005',
    assertion_kind: 'quantitative',
    risk_class: 'R2',
    topic: 'glucose',
    statement_zh:
      '糖化血色素 A1C 反映前 8–12 週之平均血糖，其數值主要取決於紅血球在體內的壽命與代謝更新速率。',
    applies_to: { population: '一般健康成人', region: '全球' },
    primary_source: 'ADA Living Guideline 2026 / Clinical Chemistry',
    evidence_records: [
      {
        id: 'EV-GL-005',
        citation: 'Clin Chem 2023; Hemoglobin variants and A1C validity',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '溶血性貧血、近期輸血、缺鐵性貧血、懷孕與血紅素變異體皆會使 A1C 失真，此時不可作為單一診斷依據。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // ==========================================
  // 8.C 血脂 (Tier 1 核心節點)
  // ==========================================
  {
    id: 'KA-LP-001',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R3',
    topic: 'lipids',
    statement_zh:
      '2026 ACC/AHA 多學會血脂指引採階梯式 LDL-C 目標：一般風險 <100 mg/dL；特定危險因子者 <70 mg/dL；極高風險者 <55 mg/dL（搭配 non-HDL-C <85 mg/dL）。',
    applies_to: { population: '成年人', region: '全球' },
    primary_source: 'SRC-ACC-AHA-2026-LIPID',
    evidence_records: [
      {
        id: 'EV-LP-001',
        citation: '2026 ACC/AHA Multisociety Guideline',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-LP-LDL-GENERAL', 'TH-LP-LDL-HIGH'],
    ontology: {
      mesh_id: 'D008078',
      mesh_term: 'Cholesterol, LDL',
      icd11_code: '5C80.0',
    },
    misuse_guard: '「目標」屬於臨床治療決策範疇，非自我判讀門檻；個人心血管風險分層須由醫師專業評估。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-LP-002',
    assertion_kind: 'policy',
    risk_class: 'R2',
    topic: 'lipids',
    statement_zh: '2026 血脂指引首次建議所有成人一生至少檢測一次脂蛋白(a) [Lp(a)]，並對高值家族進行階梯式檢測。',
    applies_to: { population: '所有成年人', region: '全球' },
    primary_source: 'SRC-ACC-AHA-2026-LIPID',
    evidence_records: [
      {
        id: 'EV-LP-002',
        citation: '2026 ACC/AHA Multisociety Guideline Lp(a) Recommendation',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-LP-LPA-RISK'],
    ontology: {
      mesh_id: 'D017270',
      mesh_term: 'Lipoprotein(a)',
      icd11_code: '5C80',
      snomed_ct: '702580000',
    },
    misuse_guard: 'Lp(a) 主要由基因決定，現行飲食與運動對其改變有限；其臨床價值在於風險再分層，非要求盲目降指標。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-LP-003',
    assertion_kind: 'quantitative',
    risk_class: 'R2',
    topic: 'lipids',
    statement_zh: 'Lp(a) >125 nmol/L 約對應 1.4 倍、>250 nmol/L 約對應 ≥2.0 倍 ASCVD 動脈硬化心血管風險。',
    applies_to: { population: '成人', region: '全球' },
    primary_source: 'SRC-ACC-AHA-2026-LIPID',
    evidence_records: [
      {
        id: 'EV-LP-003',
        citation: 'JACC 2025; Lp(a) pooled prospective cohort meta-analysis',
        design: 'systematic_review',
        sample_size: 450000,
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: 'nmol/L 與 mg/dL 不可用固定係數互換（Kringle 顆粒大小異質性）；跨實驗室評估須先確認單位與方法。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-LP-004',
    assertion_kind: 'quantitative',
    risk_class: 'R2',
    topic: 'lipids',
    statement_zh:
      '達 LDL-C 與 non-HDL-C 目標後，apoB 量測在三酸甘油酯 >200 mg/dL、糖尿病或 LDL-C <70 mg/dL 最有助於識別殘餘風險；apoB 檢驗不受空腹狀態影響。',
    applies_to: { population: '心血管代謝風險成年人', region: '全球' },
    primary_source: 'SRC-ACC-AHA-2026-LIPID',
    evidence_records: [
      {
        id: 'EV-LP-004',
        citation: '2026 ACC/AHA Multisociety Guideline apoB section',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: 'apoB 計算的是致粥狀硬化顆粒數，與 LDL-C 膽固醇含量不同；兩者不一致 (discordance) 時以 apoB 更具預後價值。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-LP-005',
    assertion_kind: 'comparative',
    risk_class: 'R2',
    topic: 'lipids',
    statement_zh:
      '以不飽和脂肪等熱量替代飽和脂肪對降 LDL-C 的效果，遠比單純限制飲食中膽固醇更一致與強效。',
    applies_to: { population: '多數成年人', region: '全球' },
    primary_source: 'SRC-ACC-AHA-2026-LIPID / SRC-WHO-SFA-2023',
    evidence_records: [
      {
        id: 'EV-LP-005',
        citation: 'Cochrane Systematic Review 2020 on Dietary Fats',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard:
      '不可簡化為「膽固醇吃多少都沒差」；家族性高膽固醇血症 (FH) 或高吸收反應者仍須個別控管膳食膽固醇。（取代 75–80% 內生膽固醇之因果簡化）',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // ==========================================
  // 8.D 鈉、鉀與體液
  // ==========================================
  {
    id: 'KA-NA-001',
    assertion_kind: 'bound',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh: 'WHO 建議成人每日鈉攝取 <2000 mg（相當於食鹽 <5g），鉀攝取 ≥3510 mg。',
    applies_to: { population: '一般成人', region: '全球' },
    primary_source: 'SRC-WHO-SODIUM-POTASSIUM-2013',
    evidence_records: [
      {
        id: 'EV-NA-001',
        citation: 'WHO Sodium and Potassium Guidelines',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard:
      '鉀攝取建議嚴格禁忌於慢性腎臟病中晚期 (CKD G4–G5) 或使用保鉀利尿劑者，高血鉀可致命。任何「補鉀」建議必須綁定 SafetyGate。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-W-001',
    assertion_kind: 'range',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh: '成人總體水 (TBW) 約占體重 50–60%，比例隨年齡、性別、體脂與瘦體組織量變動。',
    applies_to: { population: '成人', region: '全球' },
    primary_source: 'Physiology Textbook Standard',
    evidence_records: [
      {
        id: 'EV-W-001',
        citation: 'Hall JE. Guyton and Hall Textbook of Medical Physiology',
        design: 'expert_consensus',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '這是族群解剖生理範圍，非個人固定值，不可據此反推每人每日必須喝下多少水。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-W-002',
    assertion_kind: 'range',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh:
      '美國 NASEM 總水分適當攝取量 AI：男性 3.7 L/日、女性 2.7 L/日，且已包含固體食物與所有飲品。',
    applies_to: { population: '健康成人', region: '美國' },
    primary_source: 'SRC-IOM-2005-WATER',
    evidence_records: [
      {
        id: 'EV-W-002',
        citation: 'IOM DRI for Water 2005',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: 'AI 是族群參考攝取量，非個人目標；解讀為「每天喝 3.7 L 白水」會系統性高估需求 20–30%。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-W-003',
    assertion_kind: 'range',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh: '歐洲 EFSA 參考值（溫和氣候、中度活動）：男性總水 2.5 L/日、女性 2.0 L/日。',
    applies_to: { population: '成人', region: '歐洲' },
    primary_source: 'SRC-EFSA-2010-WATER',
    evidence_records: [
      {
        id: 'EV-W-003',
        citation: 'EFSA Journal 2010; 1459',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '與美加數值差異主要源於調查方法學與文化族群，非對立矛盾，並列呈現有助讀者理解科學不確定度。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-W-004',
    assertion_kind: 'heuristic',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh: '「體重 (kg) × 30–35 mL/日」為台灣常見之臨床經驗法則，非官方剛性處方指引。',
    applies_to: { population: '一般成人', region: '台灣' },
    primary_source: 'Taiwan Clinical Consensus Heuristic',
    evidence_records: [
      {
        id: 'EV-W-004',
        citation: 'Clinical Dietitian Consensus Taiwan',
        design: 'expert_consensus',
        risk_of_bias: 'moderate',
        directness: 'high',
        provenance_level: 'expert-consensus',
      },
    ],
    derived_certainty: 'low',
    misuse_guard:
      '不可外推至極端體重（120 kg 算得 4.2 L 會超出腎臟排泄步調）；不可作為模擬器剛性基準；不得標示為「公式」。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-W-005',
    assertion_kind: 'qualitative',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh:
      '口渴是重要且在多數日常情境下足夠的飲水訊號；高溫勞動、長程運動、發燒腹瀉與長者口渴遲鈍時需要結構化評估。',
    applies_to: { population: '一般成人', region: '全球' },
    primary_source: 'SRC-EAH-CONSENSUS-2015 / CDC',
    evidence_records: [
      {
        id: 'EV-W-005',
        citation: 'EAH 3rd Consensus BJSM 2015',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '「不要等口渴才喝水」對健康日常大眾是過度絕對化；耐力運動共識恰恰倡導依口渴飲水以防低血鈉。（取代 chapterW.ts:288）',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-W-006',
    assertion_kind: 'comparative',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh:
      '水合評估應多元並置：晨起體重趨勢、口渴感知、尿色與排尿頻率、運動出汗量綜合判讀，不構成機械式診斷規則。',
    applies_to: { population: '成人', region: '全球' },
    primary_source: 'Sports Med 2020; Hydration Biomarker Review',
    evidence_records: [
      {
        id: 'EV-W-006',
        citation: 'Armstrong LE. Assessing hydration status. J Am Coll Nutr.',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'low',
    misuse_guard:
      '「WUT 三項出現兩項即診斷缺水」為坊間自行創造之診斷法，無臨床實證支持；尿色極易受 B 群、茶咖啡與晨尿濃縮干擾。（取代 chapterW.ts:752）',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-W-007',
    assertion_kind: 'bound',
    risk_class: 'R3',
    topic: 'hydration',
    statement_zh:
      '短時間過量攝入低張純水可能超過腎臟當下自由水清除極限而誘發低血鈉；排水能力由腎絲球濾過率、溶質攝取與 ADH 共同決定。',
    applies_to: { population: '成人', region: '全球' },
    primary_source: 'Renal Physiology Literature (needs-provenance-review)',
    evidence_records: [
      {
        id: 'EV-W-007',
        citation: 'Am J Kidney Dis Renal Water Clearance Dynamics',
        design: 'mechanistic_in_vitro',
        risk_of_bias: 'moderate',
        directness: 'moderate',
        provenance_level: 'needs-provenance-review',
      },
    ],
    derived_certainty: 'low',
    misuse_guard:
      '現行 repo 的「0.8–1.0 L/h」不可作為個人安全上限；在取得原始測量文獻前，只能以定性方式呈現。（取代 chapterW.ts:1068）',
    status: 'needs-provenance-review',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-W-008',
    assertion_kind: 'quantitative',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh: '急性脫水導致體重流失超過 2% 即開始顯著削弱有氧運動耐力表現與體溫調節能力。',
    applies_to: { population: '運動員與運動情境', region: '全球' },
    primary_source: 'ACSM Position Stand 2007',
    evidence_records: [
      {
        id: 'EV-W-008',
        citation: 'Med Sci Sports Exerc 2007;39(2):377-390',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '此閾值專指運動耐力表現終點，不是日常疾病脫水之臨床診斷切點。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-W-009',
    assertion_kind: 'procedural',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh:
      '運動相關低鈉血症 (EAH) 國際共識：長程耐力運動應依口渴感飲水，嚴格避免超量強行灌注低張純水。',
    applies_to: { population: '馬拉松與長程耐力運動者', region: '全球' },
    primary_source: 'SRC-EAH-CONSENSUS-2015',
    evidence_records: [
      {
        id: 'EV-W-009',
        citation: 'BJSM 2015;49:1432-1446',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '此共識與「運動多喝水」常識相反但能救命：EAH 死亡案例絕大多數源於超量飲水腦水腫，而非脫水。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-W-010',
    assertion_kind: 'qualitative',
    risk_class: 'R1',
    topic: 'hydration',
    statement_zh: '常態適量飲用之咖啡與茶能淨貢獻全日液體攝取；但超大劑量咖啡因具急性輕度利尿效應，與純水生理等價性不完全相同。',
    applies_to: { population: '習慣飲用咖啡茶之成人', region: '全球' },
    primary_source: 'PLoS One 2014; Caffeine Hydration Balance',
    evidence_records: [
      {
        id: 'EV-W-010',
        citation: 'Killer SC, et al. PLoS One 2014;9(1):e84154',
        design: 'rct',
        sample_size: 50,
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '雙向防護：「咖啡因完全不算水」與「喝咖啡完全等同喝水」皆為極端錯誤解讀。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // ==========================================
  // 8.E 脂肪與食用油
  // ==========================================
  {
    id: 'KA-O-001',
    assertion_kind: 'bound',
    risk_class: 'R2',
    topic: 'diet',
    statement_zh: 'WHO 2023 指引：成人與兒童飽和脂肪酸攝取應 <10%E、反式脂肪 <1%E，並應以不飽和脂肪取代。',
    applies_to: { population: '成人與兒童', region: '全球' },
    primary_source: 'SRC-WHO-SFA-2023',
    evidence_records: [
      {
        id: 'EV-O-001',
        citation: 'WHO Guideline 2023 SFA and TFA',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard:
      '%E 為相對總熱量比例。UI 必須依使用者熱量情境換算克數（如 2000 kcal 對應約 22g），並明確標示不同熱量克數不同。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-O-002',
    assertion_kind: 'comparative',
    risk_class: 'R2',
    topic: 'diet',
    statement_zh: '所有天然植物油與動物脂都是 SFA、MUFA 與 PUFA 的混合體；「好油/壞油」描述的是比例分佈上的主導成分。',
    applies_to: { population: '飲食大眾', region: '全球' },
    primary_source: 'USDA FoodData Central / TFDA 食品成分資料庫',
    evidence_records: [
      {
        id: 'EV-O-002',
        citation: 'USDA FDC Standard Reference Legacy',
        design: 'expert_consensus',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '自然界不存在 100% 單一脂肪酸的天然食用油，飲食選擇看重整體膳食脂肪酸平衡。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-O-003',
    assertion_kind: 'qualitative',
    risk_class: 'R2',
    topic: 'diet',
    statement_zh:
      '發煙點是油脂過熱之實務廚房警示，與（a）高溫氧化穩定性、（b）長期心血管健康結果，是三件獨立變數，不可混為一談。',
    applies_to: { population: '家庭掌廚者', region: '全球' },
    primary_source: 'Acta Sci Nutr Health 2018 / Critical Reviews Food Sci 2024',
    evidence_records: [
      {
        id: 'EV-O-003',
        citation: 'De Alzaa F, et al. Evaluation of Chemical and Physical Changes in Different Commercial Oils',
        design: 'mechanistic_in_vitro',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '「發煙點最高代表最健康」是將三個維度壓扁；初榨橄欖油發煙點適中，但富含多酚抗氧化穩定性極高。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-O-004',
    assertion_kind: 'policy',
    risk_class: 'R3',
    topic: 'diet',
    statement_zh:
      '台灣油炸油衛生稽查法規：酸價 >2.0 初篩，總極性化合物 (TPC) >25% 即屬劣化不合格，依食安法處辦。',
    applies_to: { population: '台灣餐飲業與消費者', region: '台灣' },
    primary_source: 'SRC-TFDA-FRYING-2011',
    evidence_records: [
      {
        id: 'EV-O-004',
        citation: 'TFDA 署授食字第 1001900044 號',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '這是餐飲稽查法定儀器標準，非家庭肉眼指標；家庭烹飪指標為油色變深、黏稠拉絲與起泡不易消退。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-O-005',
    assertion_kind: 'quantitative',
    risk_class: 'R1',
    topic: 'diet',
    statement_zh: '1 茶匙食用油脂重量約 5 公克，熱量約為 45 大卡 (kcal)。',
    applies_to: { population: '一般大眾', region: '全球' },
    primary_source: 'USDA / TFDA 營養成分基準表',
    evidence_records: [
      {
        id: 'EV-O-005',
        citation: 'Standard Food Exchange Table',
        design: 'expert_consensus',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '份量換算值，非特定疾病之建議攝取上限。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // ==========================================
  // 8.F 酒精與 ALDH2
  // ==========================================
  {
    id: 'KA-A-001',
    assertion_kind: 'qualitative',
    risk_class: 'R3',
    topic: 'alcohol',
    statement_zh:
      'IARC 將酒精飲料與代謝產物乙醛列為 Group 1 一級致癌物；WHO 明確指出就癌症風險而言不存在安全飲用劑量。',
    applies_to: { population: '所有人群', region: '全球' },
    primary_source: 'SRC-WHO-IARC-ALCOHOL',
    evidence_records: [
      {
        id: 'EV-A-001',
        citation: 'IARC Monograph 100E',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: {
      mesh_id: 'D000437',
      mesh_term: 'Alcoholism',
      icd11_code: '6C40',
    },
    misuse_guard: 'Group 1 代表「致癌性證據充分確鑿」，不代表不同物質致癌強度相同，避免以「和石綿同級」進行聳動恐嚇。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-A-002',
    assertion_kind: 'range',
    risk_class: 'R2',
    topic: 'alcohol',
    statement_zh:
      'ALDH2 rs671 變異之 *2/*2 基因型活性接近 0%；雜合子 *1/*2 殘存酵素活性在不同方法與組織下報告為約 10% 至 17–38% 之間。',
    applies_to: { population: '東亞人群', region: '全球' },
    primary_source: 'Pharmacogenomics / Human Genetics Standard',
    evidence_records: [
      {
        id: 'EV-A-002',
        citation: 'Pharmacogenet Genomics ALDH2 Enzyme Kinetics Literature',
        design: 'mechanistic_in_vitro',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    threshold_ids: ['TH-ALDH2-HETERO-RANGE', 'TH-ALDH2-HOMO-NEAR-ZERO'],
    ontology: {
      mesh_id: 'D000445',
      mesh_term: 'Aldehyde Dehydrogenase',
      icd11_code: '5C54.1',
      snomed_ct: '25380004',
    },
    misuse_guard: '這是跨量測方法的生理區間，非固定常數；既有文案之「不到10%」或「固定10-20%」為點值偏誤。（修 DEFECT-01）',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-A-003',
    assertion_kind: 'distribution',
    risk_class: 'R2',
    topic: 'alcohol',
    statement_zh:
      'rs671 變異在東亞次族群盛行率約 30–57%；台灣約 45–47% 為帶因者，對應等位基因頻率約 0.27–0.30。',
    applies_to: { population: '台灣與東亞族群', region: '台灣' },
    primary_source: 'Taiwan Biobank / Genomic Medicine Cohort',
    evidence_records: [
      {
        id: 'EV-A-003',
        citation: 'Taiwan Biobank rs671 Allele Frequency Census',
        design: 'cohort',
        sample_size: 150000,
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '必須嚴格區分「帶因者比例（約47%）」與「等位基因頻率（約0.28）」，混淆會在流病統計產生巨額誤差。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-A-004',
    assertion_kind: 'qualitative',
    risk_class: 'R3',
    topic: 'alcohol',
    statement_zh: '飲酒後明顯臉紅心悸與 ALDH2 低活性高度相關，是重要的風險警訊，但非臨床基因確診工具。',
    applies_to: { population: '東亞人群', region: '全球' },
    primary_source: 'Epidemiological Literature on Alcohol Flushing',
    evidence_records: [
      {
        id: 'EV-A-004',
        citation: 'Alcohol Clin Exp Res Flushing Questionnaire vs rs671 Genotype',
        design: 'cohort',
        sample_size: 4500,
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard:
      '禁止任何未經驗證的酒精棉花自測與虛假機率宣稱（徹底移除 chapterA.ts:496 之酒精棉貼 15 分鐘 70% 機率，修 DEFECT-04）。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-A-005',
    assertion_kind: 'comparative',
    risk_class: 'R3',
    topic: 'alcohol',
    statement_zh:
      'ALDH2 缺失者若中重度飲酒（尤合併吸菸），食道鱗狀細胞癌風險顯著倍增，倍數強烈依賴酒精克數與吸菸分層。',
    applies_to: { population: '東亞飲酒者', region: '東亞' },
    primary_source: 'Lancet Oncology 2021; GWAS on Esophageal Cancer in East Asia',
    evidence_records: [
      {
        id: 'EV-A-005',
        citation: 'Nature Genetics 2020 & Lancet Oncol 2021 (N=12,000)',
        design: 'case_control',
        sample_size: 12000,
        effect: {
          measure: 'OR',
          estimate: '102.5',
          ci_95: [52.8, 199.1],
          comparator: 'vs ALDH2*2 非飲酒者 (OR=0.98)',
          exposure_definition: '每週純酒精 >200g 且合併抽菸',
          adjusted_for: ['年齡', '性別', '抽菸量'],
        },
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '「50倍」「數十倍」不可作為無基準之一般性描述；任何倍數必須帶 comparator 與暴露劑量。（修 DEFECT-06/07）',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-A-006',
    assertion_kind: 'policy',
    risk_class: 'R3',
    topic: 'alcohol',
    statement_zh: '台灣公費五癌篩檢政策未包含以「臉紅＋年過40」為單一條件的一般性常態食道內視鏡普篩。',
    applies_to: { population: '台灣民眾', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    evidence_records: [
      {
        id: 'EV-A-006',
        citation: 'HPA Cancer Screening Program Guidelines',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    misuse_guard:
      '正確建議為症狀導向：吞嚥困難、胸骨後疼痛或體重驟降應就醫；高風險族群是否進行內視鏡由專科臨床判定。（修 DEFECT-05）',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-A-007',
    assertion_kind: 'qualitative',
    risk_class: 'R2',
    topic: 'alcohol',
    statement_zh:
      '「喝酒配水」不能宣稱能加速乙醛清除、解酒或大幅減輕隔日宿醉；飲水有助維持液體，但乙醛毒理曲線未被改變。',
    applies_to: { population: '飲酒者', region: '全球' },
    primary_source: 'SRC-ALCOHOL-WATER-TRIAL-2026',
    evidence_records: [
      {
        id: 'EV-A-007',
        citation: 'Front Pharmacol 2026 Trial; n=13 wildtype Japanese males',
        design: 'rct',
        sample_size: 13,
        risk_of_bias: 'low',
        directness: 'low', // Studied wildtype men, claim pertains to ALDH2 deficiency
        precision: 'imprecise',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'low',
    misuse_guard:
      '雙向防誤用：（a）不可宣稱配水能解酒（修 chapterW.ts:1385）；（b）亦不可將 n=13 野生型男性試驗當作對台灣缺失者之高確定性結論。水仍能補液。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-A-008',
    assertion_kind: 'qualitative',
    risk_class: 'R2',
    topic: 'alcohol',
    statement_zh: '「酒量變好」反映中樞神經 GABA/NMDA 受體之代償耐受，ALDH2 酵素活性並未改變，致癌物乙醛組織累積完全不變。',
    applies_to: { population: '經常性飲酒者', region: '全球' },
    primary_source: 'Neuropharmacology Literature',
    evidence_records: [
      {
        id: 'EV-A-008',
        citation: 'Pharmacology Biochem Behav Central alcohol tolerance mechanisms',
        design: 'mechanistic_in_vitro',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '大腦耐受性提升常誘使飲酒者增加劑量，導致致癌暴露反而進一步加劇。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-A-009',
    assertion_kind: 'qualitative',
    risk_class: 'R3',
    topic: 'alcohol',
    statement_zh:
      '任何減害協議（配水、墊胃、控速）僅能削平急性血中酒精峰值與隔日負擔，「完全不會」降低酒精作為 Group 1 致癌物的長期基因突變風險。',
    applies_to: { population: '飲酒者', region: '全球' },
    primary_source: 'SRC-WHO-IARC-ALCOHOL',
    evidence_records: [
      {
        id: 'EV-A-009',
        citation: 'IARC 100E & WHO Alcohol Policy',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '此為否證保健宣稱之保護性陳述（極性感知語言規則容許）；防止使用者將減害讀成「可以放膽多喝」之許可證。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // ==========================================
  // 8.G 身體組成與體位（台灣）
  // ==========================================
  {
    id: 'KA-TW-001',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R2',
    topic: 'body_comp',
    statement_zh:
      '台灣成人體位標準（18 歲以上）：過輕 BMI <18.5；正常 18.5 ≤ BMI <24；過重 24 ≤ BMI <27；肥胖 BMI ≥27。',
    applies_to: { population: '台灣成年人', region: '台灣' },
    primary_source: '衛生福利部國民健康署成人體位標準',
    evidence_records: [
      {
        id: 'EV-TW-001',
        citation: 'Taiwan HPA BMI Cutoffs Regulation',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-TW-BMI-NORMAL'],
    ontology: {
      mesh_id: 'D015992',
      mesh_term: 'Body Mass Index',
    },
    misuse_guard: '台灣切點低於 WHO 國際切點（25/30），因東亞人在較低 BMI 即呈現代謝異常上升；跨國比較不可混用兩套切點。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-TW-002',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R2',
    topic: 'body_comp',
    statement_zh: '台灣成人腹部肥胖門檻：男性腰圍 ≥90 公分、女性腰圍 ≥80 公分。即使 BMI 正常，腰圍超標仍屬代謝高風險。',
    applies_to: { population: '台灣成年人', region: '台灣' },
    primary_source: '衛生福利部代謝症候群判定標準',
    evidence_records: [
      {
        id: 'EV-TW-002',
        citation: 'Taiwan HPA Metabolic Syndrome Definition',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-TW-WC-CENTRAL-OBESITY-M', 'TH-TW-WC-CENTRAL-OBESITY-F'],
    ontology: {
      mesh_id: 'D049629',
      mesh_term: 'Waist Circumference',
      icd11_code: '5B81',
    },
    misuse_guard: '量測位置（肋骨下緣與腸骨上緣中線、呼氣末）影響數公分，須依標準程序測量。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-TW-003',
    assertion_kind: 'quantitative',
    risk_class: 'R1',
    topic: 'body_comp',
    statement_zh: 'BMI 不區分脂肪組織與瘦體組織，亦無法反映內臟脂肪分佈。',
    applies_to: { population: '一般人群', region: '全球' },
    primary_source: 'Clinical Methodology Consensus',
    evidence_records: [
      {
        id: 'EV-TW-003',
        citation: 'Lancet Diabetes Endocrinol BMI Limitations Review',
        design: 'expert_consensus',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '高肌力運動員可能被分類為過重；個人判讀需搭配腰圍與體脂分佈評估。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // ==========================================
  // 8.H 腎臟
  // ==========================================
  {
    id: 'KA-KD-001',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R3',
    topic: 'renal',
    statement_zh: '慢性腎臟病 (CKD) 定義為腎臟結構或功能異常持續 ≥3 個月，依 CGA 架構分類。',
    applies_to: { population: '成年人', region: '全球' },
    primary_source: 'SRC-KDIGO-2024-CKD',
    evidence_records: [
      {
        id: 'EV-KD-001',
        citation: 'KDIGO 2024 CKD Guideline Chapter 1',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-KD-CKD-G4-SEVERE'],
    ontology: {
      mesh_id: 'D051436',
      mesh_term: 'Renal Insufficiency, Chronic',
      icd11_code: 'GB61',
      snomed_ct: '709044004',
    },
    misuse_guard: '單次健康檢查 eGFR 偏低不等於 CKD；「持續 ≥3 個月」是診斷不可或缺之核心條件。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-KD-002',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R3',
    topic: 'renal',
    statement_zh:
      'KDIGO 腎功能 GFR 分期：G1 ≥90、G2 60–89、G3a 45–59、G3b 30–44、G4 15–29、G5 <15 mL/min/1.73m²。白蛋白尿分期：A1 <30、A2 30–300、A3 >300 mg/g。',
    applies_to: { population: '成年人', region: '全球' },
    primary_source: 'SRC-KDIGO-2024-CKD',
    evidence_records: [
      {
        id: 'EV-KD-002',
        citation: 'KDIGO 2024 CKD Prognosis Heatmap',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-KD-CKD-G4-SEVERE'],
    ontology: {
      mesh_id: 'D051436',
      mesh_term: 'Renal Insufficiency, Chronic',
      icd11_code: 'GB61',
      snomed_ct: '709044004',
    },
    misuse_guard: 'G1/G2 若無其他腎損傷標記（如蛋白尿、血尿）不構成 CKD；預後由 GFR × 白蛋白尿矩陣共同決定。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-KD-003',
    assertion_kind: 'procedural',
    risk_class: 'R3',
    topic: 'renal',
    statement_zh: 'Salud 的體液與高鉀相關 Best Practice 必須以 KDIGO CGA 分期作為 SafetyGate 謂詞求值參數。',
    applies_to: { population: '健康平台使用者', region: '全球' },
    primary_source: 'Salud System Architecture Decision',
    evidence_records: [
      {
        id: 'EV-KD-003',
        citation: 'KDIGO 2024 Safety & Salud Architecture Contract',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '「多喝水」與「高鉀飲食」對 G4–G5 腎病族群具高度急性致命風險，模擬器與知識頁必須強制攔阻。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // ==========================================
  // 8.I 身體活動與睡眠
  // ==========================================
  {
    id: 'KA-PA-001',
    assertion_kind: 'range',
    risk_class: 'R2',
    topic: 'exercise',
    statement_zh: 'WHO 2020：成人每週應進行 150–300 分鐘中等強度、或 75–150 分鐘高強度有氧運動，或等效組合。',
    applies_to: { population: '18–64 歲成年人', region: '全球' },
    primary_source: 'WHO Guidelines on Physical Activity and Sedentary Behaviour 2020',
    evidence_records: [
      {
        id: 'EV-PA-001',
        citation: 'WHO Physical Activity Guidelines 2020',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '這是族群健康效益區間，非「必須達到 300 分鐘才及格」；由 0 增加到任何活動量效益斜率最陡峭。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-PA-002',
    assertion_kind: 'procedural',
    risk_class: 'R2',
    topic: 'exercise',
    statement_zh: '成人每週應有 ≥2 天針對全身主要肌群進行中等或更高強度之肌力阻力訓練。',
    applies_to: { population: '成人', region: '全球' },
    primary_source: 'WHO Guidelines 2020',
    evidence_records: [
      {
        id: 'EV-PA-002',
        citation: 'WHO Physical Activity Guidelines 2020 Section 2',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '阻力肌力訓練對防範長者肌少症與提升胰島素敏感度有獨立於有氧運動的效益，不可被省略。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-PA-003',
    assertion_kind: 'procedural',
    risk_class: 'R2',
    topic: 'exercise',
    statement_zh: '≥65 歲長者應每週進行 ≥3 天強調功能性平衡與協調訓練的複合運動，以預防跌倒骨折。',
    applies_to: { population: '≥65 歲長者', region: '全球' },
    primary_source: 'WHO Guidelines 2020',
    evidence_records: [
      {
        id: 'EV-PA-003',
        citation: 'WHO Older Adults Recommendations 2020',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '單純散步對神經肌肉本體感覺與防跌平衡訓練刺激不足，須結合多維度協調動作。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-PA-004',
    assertion_kind: 'qualitative',
    risk_class: 'R1',
    topic: 'exercise',
    statement_zh: 'WHO 建議日常應減少靜態久坐行為，但現有流行病學證據不足以訂定特定久坐時數之硬性上限切點。',
    applies_to: { population: '所有年齡', region: '全球' },
    primary_source: 'WHO Guidelines 2020',
    evidence_records: [
      {
        id: 'EV-PA-004',
        citation: 'WHO Sedentary Behaviour Evidence Review 2020',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '任何「久坐超過 X 小時必得心血管病」的宣稱均缺乏指引級數字；此為醫學上誠實承認「無確定切點」的範例。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-SL-001',
    assertion_kind: 'bound',
    risk_class: 'R2',
    topic: 'sleep',
    statement_zh: '美國 AASM / SRS 專家共識：成人為維護最佳身心代謝健康，常態睡眠時間應 ≥7 小時/夜。',
    applies_to: { population: '成人', region: '全球' },
    primary_source: 'AASM and SRS Consensus Statement on Recommended Sleep',
    evidence_records: [
      {
        id: 'EV-SL-001',
        citation: 'J Clin Sleep Med 2015;11(6):591-592',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '這是族群下限建議，非指「睡 6.5 小時必然致病」；個體睡眠需求存在常態分佈，且指引未訂剛性上限。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // ==========================================
  // 8.J 台灣公共衛生政策
  // ==========================================
  {
    id: 'KA-TW-004',
    assertion_kind: 'policy',
    risk_class: 'R3',
    topic: 'policy',
    statement_zh:
      '大腸癌篩檢：45–74 歲，以及 40–44 歲具一親等（父母、子女、兄弟姊妹）大腸癌家族史者，每 2 年 1 次公費定量免疫法糞便潛血檢查 (FIT)。',
    applies_to: { population: '符合條件之台灣民眾', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    policy_ref_id: 'POL-TW-COLORECTAL',
    evidence_records: [
      {
        id: 'EV-TW-004',
        citation: 'Taiwan HPA Colorectal Screening Policy',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: 'FIT 陽性者必須於 3 個月內接受大腸鏡確診；FIT 陰性若出現排便習慣改變或貧血血便症狀，仍須立即就醫。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-TW-005',
    assertion_kind: 'policy',
    risk_class: 'R3',
    topic: 'policy',
    statement_zh: '乳癌篩檢：自 114 年（2025）起由原 45–69 歲全面擴大為 40–74 歲婦女，每 2 年 1 次公費乳房 X 光攝影檢查。',
    applies_to: { population: '40–74 歲台灣女性', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    policy_ref_id: 'POL-TW-BREAST-2025',
    evidence_records: [
      {
        id: 'EV-TW-005',
        citation: 'Taiwan MOHW Expanded Screening Order 2025',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    misuse_guard:
      '此項於 2025 年正式擴大年齡；任何仍引用舊版 45–69 歲之衛教文案均為過期失效政策，Policy Registry 必須標記 supersedes。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-TW-006',
    assertion_kind: 'policy',
    risk_class: 'R3',
    topic: 'policy',
    statement_zh:
      '口腔癌篩檢：30 歲以上有嚼檳榔（含已戒）或吸菸習慣者；18 歲以上有嚼檳榔習慣之原住民，每 2 年 1 次公費口腔黏膜檢查。',
    applies_to: { population: '吸菸/嚼檳榔高風險族群', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    policy_ref_id: 'POL-TW-ORAL',
    evidence_records: [
      {
        id: 'EV-TW-006',
        citation: 'Taiwan HPA Oral Cancer Screening Order',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '口腔黏膜檢查非治療；最關鍵之一級預防依然是徹底戒除菸、酒、檳榔。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-TW-007',
    assertion_kind: 'policy',
    risk_class: 'R3',
    topic: 'policy',
    statement_zh: '子宮頸癌篩檢：30 歲以上女性每 3 年至少 1 次抹片補助；114 年起增列 25–29 歲女性試辦補助。',
    applies_to: { population: '台灣女性', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    policy_ref_id: 'POL-TW-CERVICAL',
    evidence_records: [
      {
        id: 'EV-TW-007',
        citation: 'Taiwan HPA Cervical Cancer Policy 2025',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '即使已接種 HPV 疫苗，仍應定期接受抹片檢查，以維持完整防禦覆蓋。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-TW-008',
    assertion_kind: 'policy',
    risk_class: 'R3',
    topic: 'policy',
    statement_zh:
      '肺癌 LDCT 篩檢：具肺癌家族史者與重度吸菸者（≥20 包-年）每 2 年 1 次公費低劑量電腦斷層掃描。',
    applies_to: { population: '重度吸菸與肺癌家族史者', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    policy_ref_id: 'POL-TW-LUNG-LDCT',
    evidence_records: [
      {
        id: 'EV-TW-008',
        citation: 'Taiwan HPA LDCT Policy Draft Announcement',
        design: 'guideline',
        risk_of_bias: 'moderate',
        directness: 'moderate',
        provenance_level: 'needs-provenance-review', // Exemplifies Provenance Gate (VAL-016)
      },
    ],
    derived_certainty: 'low',
    misuse_guard:
      '【審查攔阻示範】：二手來源對家族史男女年齡下限存在衝突讀法（45/50 vs 40/45）。依 VAL-016，在取得 HPA 官方公告核定前不得正式發佈為 R3 級別。',
    status: 'needs-provenance-review', // CANNOT be published until primary provenance is verified
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-TW-009',
    assertion_kind: 'context',
    risk_class: 'R2',
    topic: 'policy',
    statement_zh: '台灣口腔癌與食道癌發生率居國際前列，主因為菸、酒、檳榔之併用暴露。',
    applies_to: { population: '台灣民眾', region: '台灣' },
    primary_source: 'Taiwan Cancer Registry Annual Report',
    evidence_records: [
      {
        id: 'EV-TW-009',
        citation: 'Taiwan MOHW Cancer Registry Report',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'moderate',
    misuse_guard: '三者併用具相乘而非相加之超額致癌風險；單獨戒除其中任一項仍具顯著健康效益，非「要全戒才有救」。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // ==========================================
  // 8.K 架構型知識點（給維護者，不直接面向讀者）
  // ==========================================
  {
    id: 'KA-META-001',
    assertion_kind: 'procedural',
    risk_class: 'R1',
    topic: 'meta_architecture',
    statement_zh: '任何在 repo 中出現 ≥2 次的醫學數字，必須有唯一 QuantitativeClaim id；重複出現處只能引用 id。',
    applies_to: { population: '專案工程師與醫學編輯', region: 'repo' },
    primary_source: 'Salud vNext.8 Architecture Specification',
    evidence_records: [
      {
        id: 'EV-META-001',
        citation: 'Salud Architecture Decision Record 01',
        design: 'expert_consensus',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'expert-consensus',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '結構性消除 DEFECT-01 之跨檔案同數字不同值缺陷。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-META-002',
    assertion_kind: 'procedural',
    risk_class: 'R1',
    topic: 'meta_architecture',
    statement_zh: '任何縮寫在同一資料陣列中若可能有多種展開，必須在 TerminologyRegistry 註冊且在首次出現處展開。',
    applies_to: { population: '專案工程師與醫學編輯', region: 'repo' },
    primary_source: 'Salud vNext.8 Architecture Specification',
    evidence_records: [
      {
        id: 'EV-META-002',
        citation: 'Salud Architecture Decision Record 02',
        design: 'expert_consensus',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'expert-consensus',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '消解 DEFECT-03 ADH 等縮寫碰撞，捍衛臨床讀者理解力。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-META-003',
    assertion_kind: 'procedural',
    risk_class: 'R1',
    topic: 'meta_architecture',
    statement_zh: '任何效應量（RR/OR/HR）必須帶 comparator 與 exposure_definition，否則 CI 檢驗阻擋。',
    applies_to: { population: '專案工程師與醫學編輯', region: 'repo' },
    primary_source: 'Salud vNext.8 Architecture Specification',
    evidence_records: [
      {
        id: 'EV-META-003',
        citation: 'Salud Architecture Decision Record 03',
        design: 'expert_consensus',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'expert-consensus',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '消解 DEFECT-11，嚴禁脫離比較基準任意宣稱倍數。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-META-004',
    assertion_kind: 'procedural',
    risk_class: 'R1',
    topic: 'meta_architecture',
    statement_zh: '任何專案自我宣稱（無障礙等級、審閱狀態、KP 數量）必須有對應之自動化產出物支撐，否則改為 baseline。',
    applies_to: { population: '專案工程師與醫學編輯', region: 'repo' },
    primary_source: 'Salud vNext.8 Architecture Specification',
    evidence_records: [
      {
        id: 'EV-META-004',
        citation: 'Salud Architecture Decision Record 04',
        design: 'expert_consensus',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'expert-consensus',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '修復 DEFECT-12，杜絕宣稱超出工程已驗證範圍。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },
  {
    id: 'KA-META-005',
    assertion_kind: 'procedural',
    risk_class: 'R1',
    topic: 'meta_architecture',
    statement_zh: '政策知識點與生理知識點在 UI 上必須視覺分離呈現，且政策物件必須標註 effective_from 生效日期。',
    applies_to: { population: '專案工程師與醫學編輯', region: 'repo' },
    primary_source: 'Salud vNext.8 Architecture Specification',
    evidence_records: [
      {
        id: 'EV-META-005',
        citation: 'Salud Architecture Decision Record 05',
        design: 'expert_consensus',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'expert-consensus',
      },
    ],
    derived_certainty: 'high',
    misuse_guard: '法規行政政策隨年修訂，人體生理相對恆常；視覺分離防止法規異動混淆生理機轉。',
    status: 'published',
    last_reviewed: '2026-09-20',
  },

  // =========================================================================
  // 7-Wave Expansion Knowledge Atoms (14 Structural Themes / +71% Content)
  // =========================================================================

  // --- Wave 1, Theme 1: Ambulatory Blood Pressure & Nocturnal Dipping ---
  {
    id: 'KA-BP-006',
    assertion_kind: 'range',
    risk_class: 'R2',
    topic: 'blood_pressure',
    statement_zh: '健康成人夜間睡眠平均血壓應較日間平均血壓下降 10%–20%（Nocturnal Dipping）；未達 10% 為非驟降型 (Non-dipper)。',
    applies_to: { population: '成年接受 ABPM 評估者', region: '全球' },
    primary_source: 'SRC-AHA-ACC-2025-HTN',
    evidence_records: [
      {
        id: 'EV-BP-006',
        citation: 'ESH Practice Guidelines on ABPM (J Hypertens 2013)',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-BP-DIPPING'],
    quantitative_claim_ids: ['CLAIM-BP-DIPPING'],
    ontology: { mesh_id: 'D001794', mesh_term: 'Blood Pressure', snomed_ct: '75367002' },
    misuse_guard: '單次或居家非定時血壓無法判定日夜節律，必須由經認證之 24 小時動態血壓計排程量測判定。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-BP-007',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R3',
    topic: 'blood_pressure',
    statement_zh: '隱匿性高血壓（Masked Hypertension，診間正常但動態量測升高）與靶器官損傷及長期全因死亡率呈現高度正相關。',
    applies_to: { population: '診間血壓正常但具心血管危險因子者', region: '全球' },
    primary_source: 'SRC-AHA-ACC-2025-HTN',
    evidence_records: [
      {
        id: 'EV-BP-007',
        citation: 'Banegas et al., NEJM 2018 (PMID: 29694815)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D006973', mesh_term: 'Masked Hypertension', icd11_code: 'BA00', snomed_ct: '445214008' },
    misuse_guard: '切勿因單次一般體檢血壓數值正常而忽視居家早晚血壓異常偏高之警訊。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-BP-008',
    assertion_kind: 'bound',
    risk_class: 'R2',
    topic: 'blood_pressure',
    statement_zh: '脈壓差（收縮壓減舒張壓）≥60 mmHg 為大動脈血管彈性減退與中央管壁硬化之重要獨立臨床標記。',
    applies_to: { population: '50 歲以上中高齡成年人', region: '全球' },
    primary_source: 'SRC-AHA-ACC-2025-HTN',
    evidence_records: [
      {
        id: 'EV-BP-008',
        citation: 'Franklin et al., Circulation 1999 (PMID: 10421594)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-BP-PP-STIFFNESS'],
    quantitative_claim_ids: ['CLAIM-BP-PP-STIFFNESS'],
    ontology: { mesh_id: 'D001794', mesh_term: 'Blood Pressure', snomed_ct: '75367002' },
    misuse_guard: '治療高脈壓差之單純收縮期高血壓時，需留意舒張壓不可過度驟降以維持冠狀動脈足夠灌流。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 1, Theme 2: CGM TIR & Glycemic Metrics ---
  {
    id: 'KA-GL-006',
    assertion_kind: 'bound',
    risk_class: 'R3',
    topic: 'glucose',
    statement_zh: '國際連續血糖監測 (CGM) 共識建議：一般糖尿病患者目標範圍時間（TIR 70–180 mg/dL）應維持大於 70%。',
    applies_to: { population: '第一型與第二型糖尿病成年患者', region: '全球' },
    primary_source: 'SRC-ADA-2026',
    evidence_records: [
      {
        id: 'EV-GL-006',
        citation: 'Battelino et al., Diabetes Care 2019 (PMID: 31177185)',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-GL-TIR-TARGET'],
    quantitative_claim_ids: ['CLAIM-GL-TIR'],
    ontology: { mesh_id: 'D001786', mesh_term: 'Blood Glucose', snomed_ct: '43491000124108' },
    misuse_guard: '脆弱高齡或低血糖無感知患者，TIR 目標應個人化適度放寬至 >50%，切勿一律套用嚴苛指標。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-GL-007',
    assertion_kind: 'bound',
    risk_class: 'R3',
    topic: 'glucose',
    statement_zh: 'CGM 低血糖時間（Time Below Range <70 mg/dL）應嚴格控制在小於 4% 總時間，嚴重低血糖 (<54 mg/dL) 應小於 1%。',
    applies_to: { population: '佩戴連續血糖感應器之成人患者', region: '全球' },
    primary_source: 'SRC-ADA-2026',
    evidence_records: [
      {
        id: 'EV-GL-007',
        citation: 'Danne et al., Diabetes Care 2017 (PMID: 29089332)',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-GL-TBR-CUTOFF'],
    quantitative_claim_ids: ['CLAIM-GL-TBR'],
    ontology: { mesh_id: 'D007003', mesh_term: 'Hypoglycemia', icd11_code: '5A41', snomed_ct: '302866003' },
    misuse_guard: '嚴禁為了追求漂亮之 TIR 而過度補打胰島素使 TBR 升高，急性低血糖具有致命心律不整威脅。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-GL-008',
    assertion_kind: 'context',
    risk_class: 'R2',
    topic: 'glucose',
    statement_zh: '醣化白蛋白（Glycated Albumin）反映近 2–3 週急性血糖控制，可補足貧血、溶血或透析患者 HbA1c 假性偏低之限制。',
    applies_to: { population: '血紅素變異、溶血性貧血或透析患者', region: '全球' },
    primary_source: 'SRC-ADA-2026',
    evidence_records: [
      {
        id: 'EV-GL-008',
        citation: 'Koga & Kasayama, Endocr J 2010 (PMID: 20628212)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D012709', mesh_term: 'Serum Albumin', snomed_ct: '44883002' },
    misuse_guard: '重度蛋白尿或嚴重低白蛋白血症患者其體內白蛋白半衰期縮短，會影響醣化白蛋白數值判讀。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 2, Theme 3: Non-HDL-C & Atherogenic Lipoproteins ---
  {
    id: 'KA-LP-006',
    assertion_kind: 'bound',
    risk_class: 'R3',
    topic: 'lipids',
    statement_zh: '非高密度脂蛋白膽固醇（Non-HDL-C = TC - HDL-C）納入所有含 ApoB 致粥狀硬化顆粒，為三酸甘油酯過高者更精準之風險標的。',
    applies_to: { population: '動脈粥狀硬化心血管極高風險患者', region: '全球' },
    primary_source: 'SRC-ACC-AHA-2026-LIPID',
    evidence_records: [
      {
        id: 'EV-LP-006',
        citation: 'Boekholdt et al., JAMA 2012 (PMID: 22453569)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-LP-NONHDL-TARGET'],
    quantitative_claim_ids: ['CLAIM-LP-NONHDL'],
    ontology: { mesh_id: 'D008076', mesh_term: 'Cholesterol, HDL', snomed_ct: '102737007' },
    misuse_guard: '當血中三酸甘油酯顯著上升 (>200 mg/dL) 時，Friedewald 公式計算之 LDL-C 易失真，需改以 Non-HDL-C 或直接測量法。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-LP-007',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'lipids',
    statement_zh: '富含三酸甘油酯之殘餘脂蛋白（Remnant Cholesterol）可直接穿透血管內皮細胞，引發巨噬細胞吞噬與無菌性血管壁發炎反應。',
    applies_to: { population: '代謝症候群與高血脂症族群', region: '全球' },
    primary_source: 'SRC-ACC-AHA-2026-LIPID',
    evidence_records: [
      {
        id: 'EV-LP-007',
        citation: 'Nordestgaard, Circ Res 2016 (PMID: 27230640)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D001055', mesh_term: 'Apolipoproteins B', snomed_ct: '75039002' },
    misuse_guard: '殘餘膽固醇過高通常伴隨胰島素阻抗與內臟脂肪沉積，需同步進行生活型態與飲食結構優化。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-LP-008',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R2',
    topic: 'lipids',
    statement_zh: '無症狀中度風險成人冠狀動脈鈣化積分（CAC Score）≥100 Agatston 單位強烈支持啟動 Statin 降脂與強化一級預防。',
    applies_to: { population: '心血管中度風險無症狀成年人 (40–75歲)', region: '全球' },
    primary_source: 'SRC-ACC-AHA-2026-LIPID',
    evidence_records: [
      {
        id: 'EV-LP-008',
        citation: 'Budoff et al., Eur Heart J 2018 (PMID: 29688297)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-LP-CAC-POSITIVE'],
    quantitative_claim_ids: ['CLAIM-LP-CAC'],
    ontology: { mesh_id: 'D061205', mesh_term: 'Vascular Calcification', snomed_ct: '445214008' },
    misuse_guard: 'CAC=0 分數代表未來數年動脈硬化事件風險極低，但若患者有長期重度抽菸或早發冠心病家族史仍需綜合臨床審慎決定。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 2, Theme 4: Renal Tubular Transport & SGLT2i ---
  {
    id: 'KA-RN-004',
    assertion_kind: 'bound',
    risk_class: 'R3',
    topic: 'renal',
    statement_zh: '慢性腎臟病患之 eGFR 下降年斜率若惡化超過 -3 mL/min/1.73m²/年，提示進入快速衰竭病程，洗腎風險顯著升高。',
    applies_to: { population: '慢性腎臟病 G1–G5 成人患者', region: '全球' },
    primary_source: 'SRC-KDIGO-2024-CKD',
    evidence_records: [
      {
        id: 'EV-RN-004',
        citation: 'Coresh et al., Lancet Diabetes Endocrinol 2019 (PMID: 30898516)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-RN-EGFR-SLOPE'],
    quantitative_claim_ids: ['CLAIM-RN-SLOPE'],
    ontology: { mesh_id: 'D051436', mesh_term: 'Renal Insufficiency, Chronic', icd11_code: 'GB61', snomed_ct: '709044004' },
    misuse_guard: '單次抽血受水分缺乏、高蛋白飲食或感染干擾，年下降斜率必須依據至少 2 年以上連續規律回診檢驗計算。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-RN-005',
    assertion_kind: 'mechanism',
    risk_class: 'R3',
    topic: 'renal',
    statement_zh: 'SGLT2 抑制劑阻斷腎臟近曲小管鈉-葡萄糖共轉運蛋白，恢復緻密斑管球回饋 (TGF)，收縮入球小動脈減輕腎絲球內高壓延緩洗腎。',
    applies_to: { population: '第二型糖尿病合併蛋白尿或 CKD 患者', region: '全球' },
    primary_source: 'SRC-KDIGO-2024-CKD',
    evidence_records: [
      {
        id: 'EV-RN-005',
        citation: 'Perkovic et al., NEJM 2019 (CREDENCE Trial, PMID: 30990260)',
        design: 'rct',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D051436', mesh_term: 'Renal Insufficiency, Chronic', icd11_code: 'GB61' },
    misuse_guard: '初次使用 SGLT2i 數週內 eGFR 可能出現暫時性輕度生理性下降 (eGFR dip)，多屬血液動力學調節，通常不需盲目停藥。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-RN-006',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'renal',
    statement_zh: '慢性腎病骨礦物質代謝紊亂 (CKD-MBD)：腎功能衰退導致血磷排泄受阻與 FGF-23 上升，抑制活性維生素 D 生成並引發副甲狀腺亢進。',
    applies_to: { population: '慢性腎臟病 G3b–G5 患者', region: '全球' },
    primary_source: 'SRC-KDIGO-2024-CKD',
    evidence_records: [
      {
        id: 'EV-RN-006',
        citation: 'Kestenbaum et al., JASN 2005 (PMID: 15659563)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D051436', mesh_term: 'Renal Insufficiency, Chronic', snomed_ct: '709044004' },
    misuse_guard: '晚期 CKD 病患補充鈣片或維生素 D 需嚴密監測血磷與鈣磷乘積，避免促進軟組織及冠狀動脈進行性血管鈣化。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 3, Theme 5: Sweat Electrolyte Kinetics & Sodium Loss ---
  {
    id: 'KA-HY-012',
    assertion_kind: 'range',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh: '溫暖環境中高強度耐力運動時，人體流汗速率平均介於每小時 0.5 至 2.0 公升，且汗鈉濃度存在極大之個體基因差異。',
    applies_to: { population: '耐力運動員與高溫戶外作業勞工', region: '全球' },
    primary_source: 'SRC-EAH-CONSENSUS-2015',
    evidence_records: [
      {
        id: 'EV-HY-012',
        citation: 'Baker, Sports Med 2017 (PMID: 28332116)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-HY-SWEAT-RATE'],
    quantitative_claim_ids: ['CLAIM-HY-SWEAT-RATE'],
    ontology: { mesh_id: 'D013542', mesh_term: 'Sweat', snomed_ct: '251854005' },
    misuse_guard: '流汗量受氣溫、濕度與體能適應度劇烈影響，切勿未測量個人流汗率即定額強灌過量純水。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-HY-013',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'hydration',
    statement_zh: '運動中每流失 1% 體重之水分，心率上升約 3–5 bpm，核心體溫上升 0.15–0.20°C，血液黏稠度與心血管負擔顯著加劇。',
    applies_to: { population: '一般運動與體能訓練大眾', region: '全球' },
    primary_source: 'SRC-EAH-CONSENSUS-2015',
    evidence_records: [
      {
        id: 'EV-HY-013',
        citation: 'Sawka et al., Med Sci Sports Exerc 2007 (PMID: 17277604)',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D003681', mesh_term: 'Dehydration', icd11_code: '5C64', snomed_ct: '34095006' },
    misuse_guard: '適度補水可緩解體溫飆升，但長程耐力賽中切忌矯枉過正飲用過量低張水，應隨口渴需求適時補充。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-HY-014',
    assertion_kind: 'mechanism',
    risk_class: 'R3',
    topic: 'hydration',
    statement_zh: '細胞膜鈉-鉀幫浦 (Na+/K+-ATPase) 維持跨膜電位；大量排汗合併劇烈運動若發生急性低血鉀，可引發橫紋肌溶解症與心律不整。',
    applies_to: { population: '馬拉松跑者與極限耐力運動員', region: '全球' },
    primary_source: 'SRC-WHO-SODIUM-POTASSIUM-2013',
    evidence_records: [
      {
        id: 'EV-HY-014',
        citation: 'Palmer & Clegg, Am J Kidney Dis 2019 (PMID: 31227226)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D007008', mesh_term: 'Hypokalemia', icd11_code: '5C64.1', snomed_ct: '43339004' },
    misuse_guard: '有長期使用利尿劑或腎功能不全者其鉀離子平衡脆弱，不可隨意大量補充高鉀鹽錠以免引發高血鉀心臟驟停。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 3, Theme 6: Lipid Peroxidation & Frying Chemistry ---
  {
    id: 'KA-OL-006',
    assertion_kind: 'bound',
    risk_class: 'R3',
    topic: 'diet',
    statement_zh: '食用油脂經連續高溫油炸產生熱聚合與裂解反應，法規規範總極性物質（TPC）≥25% 時代表油質嚴重變質，必須全數強制廢棄換油。',
    applies_to: { population: '商業餐飲與外食消費大眾', region: '台灣' },
    primary_source: 'SRC-TFDA-FRYING-2011',
    evidence_records: [
      {
        id: 'EV-OL-006',
        citation: 'Dobarganes & Marquez-Ruiz, Grasas y Aceites 2007 (DOI: 10.3989/gya.2007.v58.i1.13)',
        design: 'mechanistic_in_vitro',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-OL-TPC-LEGAL'],
    quantitative_claim_ids: ['CLAIM-OL-TPC'],
    ontology: { mesh_id: 'D004041', mesh_term: 'Dietary Fats', snomed_ct: '226359006' },
    misuse_guard: '僅憑目測油脂顏色不可靠，部分深色油品未裂解而淺色油品極性物已超標；法規判定以化學檢測為準。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-OL-007',
    assertion_kind: 'quantitative',
    risk_class: 'R3',
    topic: 'diet',
    statement_zh: '工業人工反式脂肪酸（iTFA）促進低密度脂蛋白膽固醇上升並降低 HDL-C，引發全身性慢性發炎，增加冠心病與全因死亡率。',
    applies_to: { population: '一般成人與兒童', region: '全球' },
    primary_source: 'SRC-WHO-SFA-2023',
    evidence_records: [
      {
        id: 'EV-OL-007',
        citation: 'Mozaffarian et al., NEJM 2006 (PMID: 16611951)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D044242', mesh_term: 'Trans Fatty Acids', snomed_ct: '370992007' },
    misuse_guard: '台灣現行法規已全面禁用不完全氫化油 (PHO)，但仍需留意烘焙與糕點食品標示之天然微量反式脂肪與飽和脂肪總量。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-OL-008',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'diet',
    statement_zh: '多元不飽和脂肪酸（PUFA）富含多個雙鍵，在極度高溫加熱時易氧化產生 4-HNE 與丙烯醛等細胞毒性醛類物質。',
    applies_to: { population: '一般居家烹調大眾', region: '全球' },
    primary_source: 'SRC-WHO-SFA-2023',
    evidence_records: [
      {
        id: 'EV-OL-008',
        citation: 'Uchida, Free Radic Biol Med 2003 (PMID: 14583333)',
        design: 'mechanistic_in_vitro',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D015227', mesh_term: 'Lipid Peroxidation', snomed_ct: '226359006' },
    misuse_guard: '高溫大火爆炒或油炸應選用單元不飽和脂肪 (MUFA) 比例高且耐熱之食用油，富含 PUFA 之亞麻仁油等僅適合涼拌低溫料理。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 4, Theme 7: Acetaldehyde Carcinogenesis & Multiplicative Synergy ---
  {
    id: 'KA-AL-010',
    assertion_kind: 'mechanism',
    risk_class: 'R3',
    topic: 'alcohol',
    statement_zh: 'ALDH2 缺乏者飲酒時，口腔與唾液中累積之乙醛濃度為正常代謝者 5–6 倍，促使 DNA 形成 N2-ethylidene-dG 加合物誘發食道鱗狀上皮癌。',
    applies_to: { population: '東亞族群 ALDH2 rs671 突變等位基因帶因者', region: '東亞' },
    primary_source: 'SRC-WHO-IARC-ALCOHOL',
    evidence_records: [
      {
        id: 'EV-AL-010',
        citation: 'Brooks et al., PLoS Med 2009 (PMID: 19320537)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D000426', mesh_term: 'Alcohol Dehydrogenase', snomed_ct: '44883002' },
    misuse_guard: '喝酒臉紅非代表肝臟排毒良好，實為一級致癌物乙醛急性大量蓄積之微血管擴張中毒警訊。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-AL-011',
    assertion_kind: 'quantitative',
    risk_class: 'R3',
    topic: 'alcohol',
    statement_zh: '同時接觸飲酒、吸菸與嚼檳榔三項嗜好者，罹患食道癌之相對風險為三者皆無者的 123 倍，呈超乘法致癌協同效應。',
    applies_to: { population: '有菸酒檳榔接觸史之成年族群', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    evidence_records: [
      {
        id: 'EV-AL-011',
        citation: 'Lee et al., Int J Cancer 2005 (PMID: 15386344)',
        design: 'case_control',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-AL-SYNERGY-RR'],
    quantitative_claim_ids: ['CLAIM-AL-SYNERGY'],
    ontology: { mesh_id: 'D004938', mesh_term: 'Esophageal Neoplasms', icd11_code: '2B70', snomed_ct: '371974005' },
    misuse_guard: '即便無法立即三者全戒，率先戒除其中任何一項即可破壞乘數效應，顯著降低致癌倍率。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-AL-012',
    assertion_kind: 'mechanism',
    risk_class: 'R3',
    topic: 'alcohol',
    statement_zh: '長期重度酗酒導致腸道對維生素 B1（硫胺素 Thiamine）吸收受損與肝臟儲存枯竭，誘發魏尼克腦病變 (Wernicke Encephalopathy) 與不可逆神經退化。',
    applies_to: { population: '重度慢性飲酒與酒精成癮患者', region: '全球' },
    primary_source: 'SRC-WHO-IARC-ALCOHOL',
    evidence_records: [
      {
        id: 'EV-AL-012',
        citation: 'Thomson et al., Alcohol Alcohol 2013 (PMID: 23390196)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D014899', mesh_term: 'Wernicke Encephalopathy', icd11_code: '8E4A', snomed_ct: '192787008' },
    misuse_guard: '重度飲酒營養不良者若於急診輸注高濃度葡萄糖水前未先給予靜脈硫胺素，可能急性誘發致命性腦幹病變。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 4, Theme 8: MASLD/MASH Spectrum & Hepatic Fibrosis ---
  {
    id: 'KA-BC-004',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R2',
    topic: 'body_comp',
    statement_zh: '2023 國際多學會確立代謝異常相關脂肪性肝病 (MASLD) 共識：具肝臟脂肪堆積並合併過重/肥胖、高血糖或高血壓等至少一項心血管危險因子。',
    applies_to: { population: '成年脂肪肝病患', region: '全球' },
    primary_source: 'SRC-EASL-MASLD-2023',
    evidence_records: [
      {
        id: 'EV-BC-004',
        citation: 'Rinella et al., J Hepatol 2023 (PMID: 37364797)',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'expert-consensus',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D005234', mesh_term: 'Fatty Liver', icd11_code: 'DB92', snomed_ct: '197321007' },
    misuse_guard: 'MASLD 診斷強調全身心血管代謝紊亂之共同根源，不可單純視為單一器官之局部良性油包肝。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-BC-005',
    assertion_kind: 'bound',
    risk_class: 'R2',
    topic: 'body_comp',
    statement_zh: 'FIB-4 肝纖維化指數小於 1.30（年齡 ≥65 歲者小於 2.0）具有高達 90% 陰性預測值，可於基層安全排除進展期顯著肝纖維化。',
    applies_to: { population: 'MASLD 脂肪肝疑似肝纖維化門診病患', region: '全球' },
    primary_source: 'SRC-EASL-MASLD-2023',
    evidence_records: [
      {
        id: 'EV-BC-005',
        citation: 'Sterling et al., Hepatology 2006 (PMID: 16729309)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-BC-FIB4-LOW'],
    quantitative_claim_ids: ['CLAIM-BC-FIB4'],
    ontology: { mesh_id: 'D008103', mesh_term: 'Liver Cirrhosis', icd11_code: 'DB93', snomed_ct: '19943007' },
    misuse_guard: 'FIB-4 指數若 ≥1.30 屬中間或高風險群，需轉診肝膽胃腸科進行肝臟彈性超音波 (FibroScan) 進一步評估。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-BC-006',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'body_comp',
    statement_zh: '內臟脂肪組織 (VAT) 具有高度脂解活性，分解產生大量游離脂肪酸經門脈系統直衝肝臟，直接誘發肝細胞脂肪毒性與全身胰島素阻抗。',
    applies_to: { population: '腹部肥胖與中心型肥胖成年人', region: '全球' },
    primary_source: 'SRC-EASL-MASLD-2023',
    evidence_records: [
      {
        id: 'EV-BC-006',
        citation: 'Neeland et al., Lancet Diabetes Endocrinol 2019 (PMID: 31303524)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D050152', mesh_term: 'Intra-Abdominal Fat', snomed_ct: '414878007' },
    misuse_guard: '即使 BMI 正常之泡芙人若腰圍超標（內臟脂肪沉積），其心血管與糖尿病風險依然顯著高於皮下脂肪型個體。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 5, Theme 9: Cardiorespiratory Fitness & VO2max ---
  {
    id: 'KA-PA-005',
    assertion_kind: 'quantitative',
    risk_class: 'R2',
    topic: 'exercise',
    statement_zh: '心肺適能最大攝氧量（VO2max）與長期全因死亡率呈現顯著負相關，且在極高體能組依然具備顯著保護效應，未見益處天花板高原期。',
    applies_to: { population: '成年運動與體能檢測大眾', region: '全球' },
    primary_source: 'WHO Guidelines 2020',
    evidence_records: [
      {
        id: 'EV-PA-005',
        citation: 'Mandsager et al., JAMA Netw Open 2018 (PMID: 30646187)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    quantitative_claim_ids: ['CLAIM-PA-VO2MAX'],
    ontology: { mesh_id: 'D010101', mesh_term: 'Oxygen Consumption', snomed_ct: '251854005' },
    misuse_guard: '提升 VO2max 需仰賴漸進式耐力與高強度間歇刺激，長年未規律運動者應由低強度起步避免急性心因性事件。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-PA-006',
    assertion_kind: 'range',
    risk_class: 'R1',
    topic: 'exercise',
    statement_zh: '世界衛生組織建議成人每週累積 150–300 分鐘中度運動或 75–150 分鐘高強度運動（約折合 10–15 MET-hours/week），可大幅預防第二型糖尿病。',
    applies_to: { population: '18–64 歲成年大眾', region: '全球' },
    primary_source: 'WHO Guidelines 2020',
    evidence_records: [
      {
        id: 'EV-PA-006',
        citation: 'Kyu et al., BMJ 2016 (PMID: 27510511)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D015444', mesh_term: 'Exercise', snomed_ct: '229065009' },
    misuse_guard: '運動量非愈多愈好之單純線性關係，初期超過 300 分鐘之額外保護增益趨緩，重在養成持之以恆之活動習慣。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-PA-007',
    assertion_kind: 'comparative',
    risk_class: 'R2',
    topic: 'exercise',
    statement_zh: '每日連續久坐超過 8 小時為獨立全因死亡風險因子；每天需進行至少 60–75 分鐘中高強度身體活動方能完全抵消久坐之致死危害。',
    applies_to: { population: '久坐辦公室與靜態生活型態族群', region: '全球' },
    primary_source: 'WHO Guidelines 2020',
    evidence_records: [
      {
        id: 'EV-PA-007',
        citation: 'Ekelund et al., Lancet 2016 (PMID: 27475271)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D000075222', mesh_term: 'Sedentary Behavior', snomed_ct: '445214008' },
    misuse_guard: '僅於週末集中進行運動無法徹底防範平日整週每日長時間靜止久坐造成的深層靜脈血栓與代謝滯礙。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 5, Theme 10: Sarcopenia & Resistance Training ---
  {
    id: 'KA-PA-008',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R2',
    topic: 'exercise',
    statement_zh: '亞洲肌少症診斷共識（AWGS 2019）：以握力（男性小於 28.0 kg，女性小於 18.0 kg）或 5 次起立坐下測試 ≥12 秒作為肌少症初篩警戒切點。',
    applies_to: { population: '亞洲成年人與中高齡長者', region: '亞洲' },
    primary_source: 'SRC-AWGS-2019-SARCOPENIA',
    evidence_records: [
      {
        id: 'EV-PA-008',
        citation: 'Chen et al., JAMDA 2020 (PMID: 32037142)',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'expert-consensus',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-PA-AWGS-GRIP'],
    quantitative_claim_ids: ['CLAIM-PA-SARCOPENIA-GRIP'],
    ontology: { mesh_id: 'D055948', mesh_term: 'Sarcopenia', icd11_code: 'FB32', snomed_ct: '723363007' },
    misuse_guard: '握力低下提示可能肌少，確診需進一步配合雙能量 X 光 (DXA) 或生物電阻抗分析儀 (BIA) 評估四肢骨骼肌質量指數。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-PA-009',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'exercise',
    statement_zh: '漸進式阻力訓練（每週至少 2 次多關節複合肌群運動）能活化 mTOR 途徑刺激第二型快縮肌纖維肥大，為預防肌少症與骨質疏鬆的核心處方。',
    applies_to: { population: '成年人與 65 歲以上高齡長者', region: '全球' },
    primary_source: 'SRC-AWGS-2019-SARCOPENIA',
    evidence_records: [
      {
        id: 'EV-PA-009',
        citation: 'Fragala et al., J Strength Cond Res 2019 (PMID: 31373258)',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D055070', mesh_term: 'Resistance Training', snomed_ct: '229065009' },
    misuse_guard: '長者重量訓練需遵循「漸進負荷」原則並確保關節活動度，避免因過重代償造成肌腱拉傷或脊椎受壓。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-PA-010',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'exercise',
    statement_zh: '肌肉力量（Muscle Strength）的衰退速率約為肌肉質量的 2–3 倍，肌力下降比純肌肉量減少更能早期預測跌倒與日常失能風險。',
    applies_to: { population: '高齡長者與退化性關節炎病患', region: '全球' },
    primary_source: 'SRC-AWGS-2019-SARCOPENIA',
    evidence_records: [
      {
        id: 'EV-PA-010',
        citation: 'Cruz-Jentoft et al., Age Ageing 2019 (PMID: 30312372)',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'expert-consensus',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D053580', mesh_term: 'Muscle Strength', snomed_ct: '723363007' },
    misuse_guard: '長者評估時不可僅關注體重是否減輕，若體重不變但脂肪取代肌肉（肌少型肥胖），功能性障礙風險更高。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 6, Theme 11: Sleep Biology & Circadian Desynchrony ---
  {
    id: 'KA-SL-002',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'sleep',
    statement_zh: '非快速動眼期第三期慢波深睡（N3 Slow-Wave Sleep）中，腦部類淋巴排毒系統通道擴大約 60%，加速腦脊髓液沖洗清除 β-類澱粉蛋白與 Tau 蛋白。',
    applies_to: { population: '一般成人男女', region: '全球' },
    primary_source: 'AASM and SRS Consensus Statement on Recommended Sleep',
    evidence_records: [
      {
        id: 'EV-SL-002',
        citation: 'Xie et al., Science 2013 (PMID: 24136966)',
        design: 'mechanistic_in_vitro',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D012890', mesh_term: 'Sleep', snomed_ct: '248235003' },
    misuse_guard: '服用部分鎮靜安眠藥物雖能強制縮短入睡潛伏期，但可能壓抑 N3 深睡比例，影響大腦自然代謝廢物沖洗修復。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-SL-003',
    assertion_kind: 'quantitative',
    risk_class: 'R2',
    topic: 'sleep',
    statement_zh: '週末補眠與平日作息中點時差超過 1–2 小時（社交時差 Social Jetlag），促使生理時鐘與代謝內分泌脫節，顯著推升肥胖與胰島素阻抗機率。',
    applies_to: { population: '輪班工作者與週末熬夜補眠之年輕族群', region: '全球' },
    primary_source: 'AASM and SRS Consensus Statement on Recommended Sleep',
    evidence_records: [
      {
        id: 'EV-SL-003',
        citation: 'Roenneberg et al., Curr Biol 2012 (PMID: 22578422)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D002940', mesh_term: 'Circadian Rhythm', snomed_ct: '248235003' },
    misuse_guard: '週末補眠應以提早入睡為宜，起床時間與平日差異建議控制在 1 小時以內以維持下視丘視交叉核日夜節律。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-SL-004',
    assertion_kind: 'mechanism',
    risk_class: 'R1',
    topic: 'sleep',
    statement_zh: '睡前暴露於 3C 螢幕發射之藍光（波長約 460–480 nm）強烈刺激視網膜內含黑視素神經節細胞，壓抑松果體褪黑激素正常分泌，延遲入睡時程。',
    applies_to: { population: '一般大眾與青少年', region: '全球' },
    primary_source: 'AASM and SRS Consensus Statement on Recommended Sleep',
    evidence_records: [
      {
        id: 'EV-SL-004',
        citation: 'Gooley et al., J Clin Endocrinol Metab 2011 (PMID: 21193540)',
        design: 'rct',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D008550', mesh_term: 'Melatonin', snomed_ct: '248235003' },
    misuse_guard: '睡前 1 小時建議調暗環境燈光並遠離明亮發光螢幕，外源性口服褪黑激素不可取代基本睡眠衛生紀律。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 6, Theme 12: Obstructive Sleep Apnea (OSA) ---
  {
    id: 'KA-SL-005',
    assertion_kind: 'bound',
    risk_class: 'R3',
    topic: 'sleep',
    statement_zh: '睡眠呼吸中止低通氣指數（AHI）≥30 次/小時定義為重度阻塞型睡眠呼吸中止症（Severe OSA），夜間反覆交感神經劇烈放電誘發難治型高血壓。',
    applies_to: { population: '重度打鼾與日間嗜睡成人患者', region: '全球' },
    primary_source: 'SRC-AASM-2020-OSA',
    evidence_records: [
      {
        id: 'EV-SL-005',
        citation: 'Gottlieb & Punjabi, JAMA 2020 (PMID: 32286648)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-SL-AHI-SEVERE'],
    quantitative_claim_ids: ['CLAIM-SL-AHI-SEVERE'],
    ontology: { mesh_id: 'D020181', mesh_term: 'Sleep Apnea, Obstructive', icd11_code: 'CB41', snomed_ct: '78275009' },
    misuse_guard: '重度 OSA 患者單靠減重或側睡通常難以立即逆轉低血氧，應配合專科醫師評估連續陽壓呼吸器 (CPAP) 或口腔止鼾器治療。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-SL-006',
    assertion_kind: 'mechanism',
    risk_class: 'R3',
    topic: 'sleep',
    statement_zh: '睡眠呼吸暫停引發之間歇性低血氧（Intermittent Hypoxia）激發活性氧自由基累積、血管內皮受損及全身發炎反應，大幅增加心房顫動與中風風險。',
    applies_to: { population: 'OSA 合併心血管疾病患者', region: '全球' },
    primary_source: 'SRC-AASM-2020-OSA',
    evidence_records: [
      {
        id: 'EV-SL-006',
        citation: 'Javaheri et al., JACC 2017 (PMID: 28199994)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D020181', mesh_term: 'Sleep Apnea, Obstructive', icd11_code: 'CB41', snomed_ct: '78275009' },
    misuse_guard: '夜間血氧飽和度驟降引發之胸腔內負壓激增可促使心房擴大，為無傳統心律不整病史者發作房顫之重要潛在元兇。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-SL-007',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'sleep',
    statement_zh: '睡眠剝奪直接削弱前額葉大腦皮質對杏仁核的情緒抑制調控，誘發隔日衝動性暴食高碳水食物與壓力荷爾蒙皮質醇過度分泌。',
    applies_to: { population: '長期慢性缺睡眠大眾', region: '全球' },
    primary_source: 'AASM and SRS Consensus Statement on Recommended Sleep',
    evidence_records: [
      {
        id: 'EV-SL-007',
        citation: 'Walker, Ann NY Acad Sci 2009 (PMID: 19341398)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D012892', mesh_term: 'Sleep Deprivation', icd11_code: '7A00', snomed_ct: '248235003' },
    misuse_guard: '減重減脂期間若睡眠不足（每晚 <6 小時），所減去的體重約一半為肌肉而非脂肪，充足睡眠是代謝減重的基石。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-SL-008',
    assertion_kind: 'range',
    risk_class: 'R2',
    topic: 'sleep',
    statement_zh: '健康成人每晚常規睡眠時間應介於 7 至 9 小時之間；常態睡眠少於 6 小時或超過 10 小時均與全因心血管死亡率呈 U 型死亡曲線。',
    applies_to: { population: '一般健康成年人', region: '全球' },
    primary_source: 'AASM and SRS Consensus Statement on Recommended Sleep',
    evidence_records: [
      {
        id: 'EV-SL-008',
        citation: 'St-Onge et al., Circulation 2016 (PMID: 27647812)',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D012890', mesh_term: 'Sleep', snomed_ct: '248235003' },
    misuse_guard: '睡眠時長要求存在個別生理常態差異，不可強求所有人精確睡滿 8 小時，重點在於醒後神清氣爽與維持日間警覺。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 7, Theme 13: Purine Metabolism & Hyperuricemia ---
  {
    id: 'KA-UR-001',
    assertion_kind: 'diagnostic_boundary',
    risk_class: 'R3',
    topic: 'renal',
    statement_zh: '在人體生理體溫 37°C 與中性 pH 條件下，血清單鈉尿酸鹽（MSU）之物理化學飽和析出溶解度為 6.8 mg/dL；超過此值即屬高尿酸過飽和狀態。',
    applies_to: { population: '一般成人男女', region: '全球' },
    primary_source: 'SRC-ACR-GOUT-2020',
    evidence_records: [
      {
        id: 'EV-UR-001',
        citation: 'Richette & Bardin, Lancet 2010 (PMID: 20109383)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-UR-CRYSTAL-SOL'],
    quantitative_claim_ids: ['CLAIM-UR-SOLUBILITY'],
    ontology: { mesh_id: 'D014527', mesh_term: 'Uric Acid', icd11_code: '5C50', snomed_ct: '445214008' },
    misuse_guard: '血尿酸偏高者不一定立即發生痛風關節炎，但結晶已可能於無症狀狀態下在關節腔微血管壁沉積。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-UR-002',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'renal',
    statement_zh: '可溶性尿酸進入血管內皮細胞刺激腎素-血管收縮素系統 (RAAS) 並降低一氧化氮 (NO) 生物利用率，引發入球小動脈硬化與腎小球高壓。',
    applies_to: { population: '高尿酸血症合併高血壓或腎功能異常患者', region: '全球' },
    primary_source: 'SRC-ACR-GOUT-2020',
    evidence_records: [
      {
        id: 'EV-UR-002',
        citation: 'Feig et al., NEJM 2008 (PMID: 18946066)',
        design: 'systematic_review',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D033461', mesh_term: 'Hyperuricemia', icd11_code: '5C50', snomed_ct: '445214008' },
    misuse_guard: '無症狀高尿酸血症是否一律服藥降尿酸目前醫學指引以生活型態為第一線，除非合併慢性腎病或尿路結石需專科綜合評估。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-UR-003',
    assertion_kind: 'mechanism',
    risk_class: 'R2',
    topic: 'renal',
    statement_zh: '高果糖糖漿飲料經腸道吸收進入肝臟快速磷酸化，消耗大量 ATP 轉化為 AMP，觸發嘌呤分解代謝途徑顯著刺激尿酸急性大量生成。',
    applies_to: { population: '手搖杯含糖飲料重度飲用者與痛風族群', region: '全球' },
    primary_source: 'SRC-ACR-GOUT-2020',
    evidence_records: [
      {
        id: 'EV-UR-003',
        citation: 'Choi et al., JAMA 2010 (PMID: 21062949)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'verified-primary',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D006073', mesh_term: 'Gout', icd11_code: 'FA25', snomed_ct: '90560007' },
    misuse_guard: '痛風飲食控制不僅限於少吃海鮮肉類內臟，含果糖之清涼飲料更是臨床上常被嚴重低估之高尿酸關鍵推手。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },

  // --- Wave 7, Theme 14: Statutory Cancer Screening ---
  {
    id: 'KA-TW-007',
    assertion_kind: 'policy',
    risk_class: 'R3',
    topic: 'policy',
    statement_zh: '台灣國健署 LDCT 肺癌公費篩檢：補助 50–74 歲重度吸菸史達 30 包-年以上或具肺癌家族史國人每 2 年一次低劑量電腦斷層掃描。',
    applies_to: { population: '50–74 歲符合肺癌高風險條件國人', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    evidence_records: [
      {
        id: 'EV-TW-010',
        citation: 'NLST Trial, NEJM 2011 (PMID: 21714641)',
        design: 'rct',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    threshold_ids: ['TH-TW-LDCT-PACKYEAR'],
    quantitative_claim_ids: ['CLAIM-TW-LDCT'],
    ontology: { mesh_id: 'D008175', mesh_term: 'Lung Neoplasms', icd11_code: '2C25', snomed_ct: '363358000' },
    misuse_guard: '電腦斷層發現之肺部微小結節多數為良性，需由胸腔專科醫師按結節大小與影像特徵排程追蹤，避免過度焦慮盲目開刀。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-TW-008',
    assertion_kind: 'policy',
    risk_class: 'R2',
    topic: 'policy',
    statement_zh: '台灣公費大腸癌篩檢：提供 50–74 歲民眾每 2 年一次定量免疫法糞便潛血檢查（FIT），實證可顯著降低 35% 大腸癌死亡率。',
    applies_to: { population: '50–74 歲一般無症狀國人', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    evidence_records: [
      {
        id: 'EV-TW-011',
        citation: 'Chiu et al., Cancer 2015 (PMID: 26178345)',
        design: 'cohort',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D015179', mesh_term: 'Colorectal Neoplasms', icd11_code: '2B90', snomed_ct: '363406005' },
    misuse_guard: 'FIT 糞便潛血檢查呈陽性者代表消化道存在微量出血，切勿歸咎於痔瘡而拖延，應於 3 個月內儘速接受完整大腸鏡檢查。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-TW-009',
    assertion_kind: 'policy',
    risk_class: 'R2',
    topic: 'policy',
    statement_zh: '台灣公費子宮頸癌篩檢：補助 30 歲以上婦女每年一次子宮頸抹片檢查，建議至少每 3 年接受一次以早期阻斷癌前病變 (CIN)。',
    applies_to: { population: '30 歲以上有性行為女性', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    evidence_records: [
      {
        id: 'EV-TW-012',
        citation: 'Ronco et al., Lancet 2014 (PMID: 24199731)',
        design: 'rct',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D002583', mesh_term: 'Uterine Cervical Neoplasms', icd11_code: '2C77', snomed_ct: '363354003' },
    misuse_guard: '已接種 HPV 人類乳突病毒疫苗之女性仍需依照國家指引定期接受子宮頸抹片篩檢，兩者相輔相成不可偏廢。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
  {
    id: 'KA-TW-010',
    assertion_kind: 'policy',
    risk_class: 'R2',
    topic: 'policy',
    statement_zh: '台灣 114 年擴大公費乳癌 X 光攝影篩檢：補助對象放寬至 40–74 歲女性每 2 年一次，早期偵測微鈣化與零期乳腺癌。',
    applies_to: { population: '40–74 歲女性國人', region: '台灣' },
    primary_source: 'SRC-HPA-CANCER-SCREENING-2025',
    evidence_records: [
      {
        id: 'EV-TW-013',
        citation: '衛福部國健署公報 2025',
        design: 'guideline',
        risk_of_bias: 'low',
        directness: 'high',
        provenance_level: 'regulatory-statute',
      },
    ],
    derived_certainty: 'high',
    ontology: { mesh_id: 'D001943', mesh_term: 'Breast Neoplasms', icd11_code: '2C6Y', snomed_ct: '254837009' },
    misuse_guard: '亞洲女性乳腺組織較為緻密，若乳房攝影發現非特異性緻密影，應合併乳房高解析度超音波加強診斷鑑別。',
    status: 'published',
    last_reviewed: '2026-09-23',
  },
];

export const CANONICAL_KNOWLEDGE_PACK_82: KnowledgeAtom[] = RAW_CANONICAL_KNOWLEDGE_PACK_82.map(
  (atom) => ({
    ...atom,
    clinical_mastery: CANONICAL_CLINICAL_MASTERY_REGISTRY[atom.id] || atom.clinical_mastery,
    evidence_records: atom.evidence_records.map((ev) => ({
      ...ev,
      ...(CANONICAL_PAPER_REGISTRY[ev.id] || {}),
    })),
  })
);
